package types

import (
	"time"

	"github.com/google/uuid"
)

// InsightTopic represents a topic category for insights
type InsightTopic struct {
	ID              uuid.UUID
	OrganizationID  *uuid.UUID
	Name            string
	Description     *string
	Keywords        []string
	Embedding       []float32
	IsAutoGenerated bool
	ContentCount    int
	LastInsightAt   *time.Time
	Color           *string
	Icon            *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// ContentTopicMatch represents the relationship between content and topics
type ContentTopicMatch struct {
	ID              uuid.UUID
	ContentID       uuid.UUID
	TopicID         uuid.UUID
	SimilarityScore float64
	IsPrimary       bool
	CreatedAt       time.Time
}

// Insight represents a generated insight/mini-blog
type Insight struct {
	ID               uuid.UUID
	OrganizationID   *uuid.UUID
	TopicID          *uuid.UUID
	Title            string
	Summary          string
	Content          *string
	KeyPoints        []string
	SourceContentIDs []uuid.UUID
	Embedding        []float32
	GeneratedAt      time.Time
	PeriodStart      *time.Time
	PeriodEnd        *time.Time
	IsRead           bool
	IsPinned         bool
	IsUsedInArticle  bool
	MetaData         map[string]interface{}
}

// UserInsightStatus represents a user's interaction status with an insight
type UserInsightStatus struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	InsightID       uuid.UUID
	IsRead          bool
	IsPinned        bool
	IsUsedInArticle bool
	ReadAt          *time.Time
	CreatedAt       time.Time
}
