# dataabases

services:
  postgres:
    image: postgres:16.4
    container_name: ${POSTGRES_CONTAINER_NAME:-postgres}
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-myapp}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgrespass}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ${POSTGRES_DATA_DIR:-/var/lib/docker/postgresql/data}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4.1
    container_name: ${REDIS_CONTAINER_NAME:-redis}
    command: redis-server --requirepass ${REDIS_PASSWORD:-redispass}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ${REDIS_DATA_DIR:-/var/lib/docker/redis/data}:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
