// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthDeleteAccountData, AuthDeleteAccountErrors, AuthDeleteAccountResponses, AuthLoginData, AuthLoginErrors, AuthLoginResponses, AuthLogoutData, AuthLogoutResponses, AuthRegisterData, AuthRegisterErrors, AuthRegisterResponses, AuthUpdateAccountData, AuthUpdateAccountErrors, AuthUpdateAccountResponses, AuthUpdatePasswordData, AuthUpdatePasswordErrors, AuthUpdatePasswordResponses, ConnectWebSocketData, ConnectWebSocketErrors, HealthCheckData, HealthCheckResponses, RootStatusData, RootStatusResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class System {
    public static rootStatus<ThrowOnError extends boolean = false>(options?: Options<RootStatusData, ThrowOnError>) {
        return (options?.client ?? client).get<RootStatusResponses, unknown, ThrowOnError>({ url: '/', ...options });
    }
    
    public static healthCheck<ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>) {
        return (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({ url: '/health', ...options });
    }
}

export class Auth {
    public static authDeleteAccount<ThrowOnError extends boolean = false>(options: Options<AuthDeleteAccountData, ThrowOnError>) {
        return (options.client ?? client).delete<AuthDeleteAccountResponses, AuthDeleteAccountErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/auth/account',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static authUpdateAccount<ThrowOnError extends boolean = false>(options: Options<AuthUpdateAccountData, ThrowOnError>) {
        return (options.client ?? client).put<AuthUpdateAccountResponses, AuthUpdateAccountErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/auth/account',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static authLogin<ThrowOnError extends boolean = false>(options: Options<AuthLoginData, ThrowOnError>) {
        return (options.client ?? client).post<AuthLoginResponses, AuthLoginErrors, ThrowOnError>({
            url: '/auth/login',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static authLogout<ThrowOnError extends boolean = false>(options?: Options<AuthLogoutData, ThrowOnError>) {
        return (options?.client ?? client).post<AuthLogoutResponses, unknown, ThrowOnError>({ url: '/auth/logout', ...options });
    }
    
    public static authUpdatePassword<ThrowOnError extends boolean = false>(options: Options<AuthUpdatePasswordData, ThrowOnError>) {
        return (options.client ?? client).put<AuthUpdatePasswordResponses, AuthUpdatePasswordErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/auth/password',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static authRegister<ThrowOnError extends boolean = false>(options: Options<AuthRegisterData, ThrowOnError>) {
        return (options.client ?? client).post<AuthRegisterResponses, AuthRegisterErrors, ThrowOnError>({
            url: '/auth/register',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class Agent {
    public static connectWebSocket<ThrowOnError extends boolean = false>(options?: Options<ConnectWebSocketData, ThrowOnError>) {
        return (options?.client ?? client).get<unknown, ConnectWebSocketErrors, ThrowOnError>({ url: '/websocket', ...options });
    }
}
