// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteAuthAccountData, DeleteAuthAccountErrors, DeleteAuthAccountResponses, DeleteBlogArticlesByIdData, DeleteBlogArticlesByIdErrors, DeleteBlogArticlesByIdResponses, GetBlogArticlesByIdRecommendedData, GetBlogArticlesByIdRecommendedErrors, GetBlogArticlesByIdRecommendedResponses, GetBlogArticlesBySlugData, GetBlogArticlesBySlugErrors, GetBlogArticlesBySlugResponses, GetBlogArticlesBySlugVersionsData, GetBlogArticlesBySlugVersionsErrors, GetBlogArticlesBySlugVersionsResponses, GetBlogArticlesData, GetBlogArticlesErrors, GetBlogArticlesResponses, GetBlogArticlesSearchData, GetBlogArticlesSearchErrors, GetBlogArticlesSearchResponses, GetBlogArticlesVersionsByVersionIdData, GetBlogArticlesVersionsByVersionIdErrors, GetBlogArticlesVersionsByVersionIdResponses, GetBlogTagsPopularData, GetBlogTagsPopularErrors, GetBlogTagsPopularResponses, PostAuthLoginData, PostAuthLoginErrors, PostAuthLoginResponses, PostAuthLogoutData, PostAuthLogoutResponses, PostAuthRegisterData, PostAuthRegisterErrors, PostAuthRegisterResponses, PostBlogArticlesBySlugPublishData, PostBlogArticlesBySlugPublishErrors, PostBlogArticlesBySlugPublishResponses, PostBlogArticlesBySlugRevertByVersionIdData, PostBlogArticlesBySlugRevertByVersionIdErrors, PostBlogArticlesBySlugRevertByVersionIdResponses, PostBlogArticlesBySlugUnpublishData, PostBlogArticlesBySlugUnpublishErrors, PostBlogArticlesBySlugUnpublishResponses, PostBlogArticlesBySlugUpdateData, PostBlogArticlesBySlugUpdateErrors, PostBlogArticlesBySlugUpdateResponses, PostBlogArticlesData, PostBlogArticlesErrors, PostBlogArticlesResponses, PostBlogGenerateData, PostBlogGenerateErrors, PostBlogGenerateResponses, PutAuthAccountData, PutAuthAccountErrors, PutAuthAccountResponses, PutAuthPasswordData, PutAuthPasswordErrors, PutAuthPasswordResponses, PutBlogByIdUpdateData, PutBlogByIdUpdateErrors, PutBlogByIdUpdateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Auth {
    /**
     * Delete account
     *
     * Permanently delete current user's account
     */
    public static deleteAuthAccount<ThrowOnError extends boolean = false>(options: Options<DeleteAuthAccountData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteAuthAccountResponses, DeleteAuthAccountErrors, ThrowOnError>({
            security: [{ name: 'Authorization', type: 'apiKey' }],
            url: '/auth/account',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Update account
     *
     * Update current user's account details
     */
    public static putAuthAccount<ThrowOnError extends boolean = false>(options: Options<PutAuthAccountData, ThrowOnError>) {
        return (options.client ?? client).put<PutAuthAccountResponses, PutAuthAccountErrors, ThrowOnError>({
            security: [{ name: 'Authorization', type: 'apiKey' }],
            url: '/auth/account',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * User login
     *
     * Authenticate user and return JWT token
     */
    public static postAuthLogin<ThrowOnError extends boolean = false>(options: Options<PostAuthLoginData, ThrowOnError>) {
        return (options.client ?? client).post<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError>({
            url: '/auth/login',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * User logout
     *
     * Logout current user session
     */
    public static postAuthLogout<ThrowOnError extends boolean = false>(options?: Options<PostAuthLogoutData, ThrowOnError>) {
        return (options?.client ?? client).post<PostAuthLogoutResponses, unknown, ThrowOnError>({
            security: [{ name: 'Authorization', type: 'apiKey' }],
            url: '/auth/logout',
            ...options
        });
    }
    
    /**
     * Update password
     *
     * Update current user's password
     */
    public static putAuthPassword<ThrowOnError extends boolean = false>(options: Options<PutAuthPasswordData, ThrowOnError>) {
        return (options.client ?? client).put<PutAuthPasswordResponses, PutAuthPasswordErrors, ThrowOnError>({
            security: [{ name: 'Authorization', type: 'apiKey' }],
            url: '/auth/password',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * User registration
     *
     * Register a new user account
     */
    public static postAuthRegister<ThrowOnError extends boolean = false>(options: Options<PostAuthRegisterData, ThrowOnError>) {
        return (options.client ?? client).post<PostAuthRegisterResponses, PostAuthRegisterErrors, ThrowOnError>({
            url: '/auth/register',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class Articles {
    /**
     * List articles
     *
     * Get a paginated list of articles with optional filtering
     */
    public static getBlogArticles<ThrowOnError extends boolean = false>(options?: Options<GetBlogArticlesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetBlogArticlesResponses, GetBlogArticlesErrors, ThrowOnError>({ url: '/blog/articles', ...options });
    }
    
    /**
     * Create new article
     *
     * Create a new blog article
     */
    public static postBlogArticles<ThrowOnError extends boolean = false>(options: Options<PostBlogArticlesData, ThrowOnError>) {
        return (options.client ?? client).post<PostBlogArticlesResponses, PostBlogArticlesErrors, ThrowOnError>({
            security: [{ name: 'Authorization', type: 'apiKey' }],
            url: '/blog/articles',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Search articles
     *
     * Search articles by query string
     */
    public static getBlogArticlesSearch<ThrowOnError extends boolean = false>(options: Options<GetBlogArticlesSearchData, ThrowOnError>) {
        return (options.client ?? client).get<GetBlogArticlesSearchResponses, GetBlogArticlesSearchErrors, ThrowOnError>({ url: '/blog/articles/search', ...options });
    }
    
    /**
     * Get article version
     *
     * Get a specific version of an article
     */
    public static getBlogArticlesVersionsByVersionId<ThrowOnError extends boolean = false>(options: Options<GetBlogArticlesVersionsByVersionIdData, ThrowOnError>) {
        return (options.client ?? client).get<GetBlogArticlesVersionsByVersionIdResponses, GetBlogArticlesVersionsByVersionIdErrors, ThrowOnError>({
            security: [{ name: 'Authorization', type: 'apiKey' }],
            url: '/blog/articles/versions/{versionId}',
            ...options
        });
    }
    
    /**
     * Delete article
     *
     * Permanently delete an article
     */
    public static deleteBlogArticlesById<ThrowOnError extends boolean = false>(options: Options<DeleteBlogArticlesByIdData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteBlogArticlesByIdResponses, DeleteBlogArticlesByIdErrors, ThrowOnError>({
            security: [{ name: 'Authorization', type: 'apiKey' }],
            url: '/blog/articles/{id}',
            ...options
        });
    }
    
    /**
     * Get recommended articles
     *
     * Get articles recommended based on the current article
     */
    public static getBlogArticlesByIdRecommended<ThrowOnError extends boolean = false>(options: Options<GetBlogArticlesByIdRecommendedData, ThrowOnError>) {
        return (options.client ?? client).get<GetBlogArticlesByIdRecommendedResponses, GetBlogArticlesByIdRecommendedErrors, ThrowOnError>({ url: '/blog/articles/{id}/recommended', ...options });
    }
    
    /**
     * Get article by slug
     *
     * Get a single article by its slug
     */
    public static getBlogArticlesBySlug<ThrowOnError extends boolean = false>(options: Options<GetBlogArticlesBySlugData, ThrowOnError>) {
        return (options.client ?? client).get<GetBlogArticlesBySlugResponses, GetBlogArticlesBySlugErrors, ThrowOnError>({ url: '/blog/articles/{slug}', ...options });
    }
    
    /**
     * Publish article
     *
     * Publish an article's draft to make it publicly visible
     */
    public static postBlogArticlesBySlugPublish<ThrowOnError extends boolean = false>(options: Options<PostBlogArticlesBySlugPublishData, ThrowOnError>) {
        return (options.client ?? client).post<PostBlogArticlesBySlugPublishResponses, PostBlogArticlesBySlugPublishErrors, ThrowOnError>({
            security: [{ name: 'Authorization', type: 'apiKey' }],
            url: '/blog/articles/{slug}/publish',
            ...options
        });
    }
    
    /**
     * Revert article to version
     *
     * Revert an article's draft to a previous version
     */
    public static postBlogArticlesBySlugRevertByVersionId<ThrowOnError extends boolean = false>(options: Options<PostBlogArticlesBySlugRevertByVersionIdData, ThrowOnError>) {
        return (options.client ?? client).post<PostBlogArticlesBySlugRevertByVersionIdResponses, PostBlogArticlesBySlugRevertByVersionIdErrors, ThrowOnError>({
            security: [{ name: 'Authorization', type: 'apiKey' }],
            url: '/blog/articles/{slug}/revert/{versionId}',
            ...options
        });
    }
    
    /**
     * Unpublish article
     *
     * Unpublish an article, making it no longer publicly visible
     */
    public static postBlogArticlesBySlugUnpublish<ThrowOnError extends boolean = false>(options: Options<PostBlogArticlesBySlugUnpublishData, ThrowOnError>) {
        return (options.client ?? client).post<PostBlogArticlesBySlugUnpublishResponses, PostBlogArticlesBySlugUnpublishErrors, ThrowOnError>({
            security: [{ name: 'Authorization', type: 'apiKey' }],
            url: '/blog/articles/{slug}/unpublish',
            ...options
        });
    }
    
    /**
     * Update article draft
     *
     * Update the draft content of an existing article
     */
    public static postBlogArticlesBySlugUpdate<ThrowOnError extends boolean = false>(options: Options<PostBlogArticlesBySlugUpdateData, ThrowOnError>) {
        return (options.client ?? client).post<PostBlogArticlesBySlugUpdateResponses, PostBlogArticlesBySlugUpdateErrors, ThrowOnError>({
            security: [{ name: 'Authorization', type: 'apiKey' }],
            url: '/blog/articles/{slug}/update',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * List article versions
     *
     * Get all versions of an article
     */
    public static getBlogArticlesBySlugVersions<ThrowOnError extends boolean = false>(options: Options<GetBlogArticlesBySlugVersionsData, ThrowOnError>) {
        return (options.client ?? client).get<GetBlogArticlesBySlugVersionsResponses, GetBlogArticlesBySlugVersionsErrors, ThrowOnError>({
            security: [{ name: 'Authorization', type: 'apiKey' }],
            url: '/blog/articles/{slug}/versions',
            ...options
        });
    }
    
    /**
     * Generate article with AI
     *
     * Generate a new blog article using AI based on the provided prompt
     */
    public static postBlogGenerate<ThrowOnError extends boolean = false>(options: Options<PostBlogGenerateData, ThrowOnError>) {
        return (options.client ?? client).post<PostBlogGenerateResponses, PostBlogGenerateErrors, ThrowOnError>({
            security: [{ name: 'Authorization', type: 'apiKey' }],
            url: '/blog/generate',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get popular tags
     *
     * Get a list of most used tags
     */
    public static getBlogTagsPopular<ThrowOnError extends boolean = false>(options?: Options<GetBlogTagsPopularData, ThrowOnError>) {
        return (options?.client ?? client).get<GetBlogTagsPopularResponses, GetBlogTagsPopularErrors, ThrowOnError>({ url: '/blog/tags/popular', ...options });
    }
    
    /**
     * Update article with AI context
     *
     * Update article using AI-powered context-aware editing
     */
    public static putBlogByIdUpdate<ThrowOnError extends boolean = false>(options: Options<PutBlogByIdUpdateData, ThrowOnError>) {
        return (options.client ?? client).put<PutBlogByIdUpdateResponses, PutBlogByIdUpdateErrors, ThrowOnError>({
            security: [{ name: 'Authorization', type: 'apiKey' }],
            url: '/blog/{id}/update',
            ...options
        });
    }
}
