// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'localhost:8080/' | (string & {});
};

export type DtoArticleListResponse = {
    articles?: Array<DtoArticleResponse>;
    page?: number;
    per_page?: number;
    total?: number;
    total_pages?: number;
};

export type DtoArticleResponse = {
    /**
     * Metadata
     */
    created_at?: string;
    draft_content?: string;
    draft_image_url?: string;
    /**
     * Draft content (for editing)
     */
    draft_title?: string;
    id?: string;
    published_at?: string;
    published_content?: string;
    published_image_url?: string;
    /**
     * Published content (for public viewing)
     */
    published_title?: string;
    /**
     * Common fields
     */
    slug?: string;
    tags?: Array<string>;
    updated_at?: string;
};

export type DtoArticleVersionListResponse = {
    total?: number;
    versions?: Array<DtoArticleVersionResponse>;
};

export type DtoArticleVersionResponse = {
    article_id?: string;
    content?: string;
    created_at?: string;
    id?: string;
    image_url?: string;
    status?: string;
    title?: string;
    version_number?: number;
};

export type DtoCreateArticleRequest = {
    content: string;
    image_url?: string;
    publish?: boolean;
    slug?: string;
    tags?: Array<string>;
    title: string;
};

export type DtoCreateOrganizationRequest = {
    bio?: string;
    email_public?: string;
    logo_url?: string;
    meta_description?: string;
    name: string;
    slug?: string;
    social_links?: {
        [key: string]: unknown;
    };
    website_url?: string;
};

export type DtoCreatePageRequest = {
    content?: string;
    is_published?: boolean;
    slug: string;
    title: string;
};

export type DtoCreateProjectRequest = {
    content?: string;
    description: string;
    image_url?: string;
    tags?: Array<string>;
    title: string;
    url?: string;
};

export type DtoCreateSourceRequest = {
    article_id: string;
    content?: string;
    meta_data?: {
        [key: string]: unknown;
    };
    source_type?: 'web' | 'pdf' | 'document' | 'note';
    title: string;
    url?: string;
};

export type DtoLoginRequest = {
    email: string;
    password: string;
};

export type DtoLoginResponse = {
    token?: string;
    user?: DtoUserResponse;
};

export type DtoOrganizationResponse = {
    bio?: string;
    created_at?: string;
    email_public?: string;
    id?: string;
    logo_url?: string;
    meta_description?: string;
    name?: string;
    slug?: string;
    social_links?: {
        [key: string]: unknown;
    };
    updated_at?: string;
    website_url?: string;
};

export type DtoPageListResponse = {
    page?: number;
    pages?: Array<DtoPageResponse>;
    per_page?: number;
    total?: number;
    total_pages?: number;
};

export type DtoPageResponse = {
    content?: string;
    created_at?: string;
    id?: string;
    is_published?: boolean;
    slug?: string;
    title?: string;
    updated_at?: string;
};

export type DtoProjectListResponse = {
    page?: number;
    per_page?: number;
    projects?: Array<DtoProjectResponse>;
    total?: number;
    total_pages?: number;
};

export type DtoProjectResponse = {
    content?: string;
    created_at?: string;
    description?: string;
    id?: string;
    image_url?: string;
    tags?: Array<string>;
    title?: string;
    updated_at?: string;
    url?: string;
};

export type DtoRegisterRequest = {
    email: string;
    name: string;
    password: string;
};

export type DtoSourceResponse = {
    article_id?: string;
    content?: string;
    created_at?: string;
    id?: string;
    meta_data?: {
        [key: string]: unknown;
    };
    source_type?: string;
    title?: string;
    updated_at?: string;
    url?: string;
};

export type DtoUpdateAccountRequest = {
    email: string;
    name: string;
};

export type DtoUpdateArticleRequest = {
    content?: string;
    image_url?: string;
    slug?: string;
    tags?: Array<string>;
    title?: string;
};

export type DtoUpdateOrganizationRequest = {
    bio?: string;
    email_public?: string;
    logo_url?: string;
    meta_description?: string;
    name?: string;
    slug?: string;
    social_links?: {
        [key: string]: unknown;
    };
    website_url?: string;
};

export type DtoUpdatePageRequest = {
    content?: string;
    is_published?: boolean;
    slug?: string;
    title?: string;
};

export type DtoUpdatePasswordRequest = {
    current_password: string;
    new_password: string;
};

export type DtoUpdateProjectRequest = {
    content?: string;
    description?: string;
    image_url?: string;
    tags?: Array<string>;
    title?: string;
    url?: string;
};

export type DtoUpdateSourceRequest = {
    content?: string;
    meta_data?: {
        [key: string]: unknown;
    };
    source_type?: 'web' | 'pdf' | 'document' | 'note';
    title?: string;
    url?: string;
};

export type DtoUserResponse = {
    email?: string;
    id?: string;
    name?: string;
    role?: string;
};

export type ResponseSuccessResponse = {
    data?: unknown;
    message?: string;
};

export type StorageCreateFolderRequest = {
    path?: string;
};

export type StorageUpdateFolderRequest = {
    newPath?: string;
    oldPath?: string;
};

export type PostAgentData = {
    /**
     * Chat request
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/agent';
};

export type PostAgentErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PostAgentError = PostAgentErrors[keyof PostAgentErrors];

export type PostAgentResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: {
            request_id?: string;
            status?: string;
        };
    };
};

export type PostAgentResponse = PostAgentResponses[keyof PostAgentResponses];

export type GetAgentArtifactsByArticleIdPendingData = {
    body?: never;
    path: {
        /**
         * Article ID
         */
        articleId: string;
    };
    query?: never;
    url: '/agent/artifacts/{articleId}/pending';
};

export type GetAgentArtifactsByArticleIdPendingErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type GetAgentArtifactsByArticleIdPendingError = GetAgentArtifactsByArticleIdPendingErrors[keyof GetAgentArtifactsByArticleIdPendingErrors];

export type GetAgentArtifactsByArticleIdPendingResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: {
            artifacts?: Array<{
                [key: string]: unknown;
            }>;
        };
    };
};

export type GetAgentArtifactsByArticleIdPendingResponse = GetAgentArtifactsByArticleIdPendingResponses[keyof GetAgentArtifactsByArticleIdPendingResponses];

export type PostAgentArtifactsByMessageIdAcceptData = {
    /**
     * Optional feedback
     */
    body?: {
        feedback?: string;
    };
    path: {
        /**
         * Message ID
         */
        messageId: string;
    };
    query?: never;
    url: '/agent/artifacts/{messageId}/accept';
};

export type PostAgentArtifactsByMessageIdAcceptErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PostAgentArtifactsByMessageIdAcceptError = PostAgentArtifactsByMessageIdAcceptErrors[keyof PostAgentArtifactsByMessageIdAcceptErrors];

export type PostAgentArtifactsByMessageIdAcceptResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: {
            success?: boolean;
        };
    };
};

export type PostAgentArtifactsByMessageIdAcceptResponse = PostAgentArtifactsByMessageIdAcceptResponses[keyof PostAgentArtifactsByMessageIdAcceptResponses];

export type PostAgentArtifactsByMessageIdRejectData = {
    /**
     * Optional feedback
     */
    body?: {
        feedback?: string;
    };
    path: {
        /**
         * Message ID
         */
        messageId: string;
    };
    query?: never;
    url: '/agent/artifacts/{messageId}/reject';
};

export type PostAgentArtifactsByMessageIdRejectErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PostAgentArtifactsByMessageIdRejectError = PostAgentArtifactsByMessageIdRejectErrors[keyof PostAgentArtifactsByMessageIdRejectErrors];

export type PostAgentArtifactsByMessageIdRejectResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: {
            success?: boolean;
        };
    };
};

export type PostAgentArtifactsByMessageIdRejectResponse = PostAgentArtifactsByMessageIdRejectResponses[keyof PostAgentArtifactsByMessageIdRejectResponses];

export type DeleteAgentConversationsByArticleIdData = {
    body?: never;
    path: {
        /**
         * Article ID
         */
        articleId: string;
    };
    query?: never;
    url: '/agent/conversations/{articleId}';
};

export type DeleteAgentConversationsByArticleIdErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type DeleteAgentConversationsByArticleIdError = DeleteAgentConversationsByArticleIdErrors[keyof DeleteAgentConversationsByArticleIdErrors];

export type DeleteAgentConversationsByArticleIdResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: {
            success?: boolean;
        };
    };
};

export type DeleteAgentConversationsByArticleIdResponse = DeleteAgentConversationsByArticleIdResponses[keyof DeleteAgentConversationsByArticleIdResponses];

export type GetAgentConversationsByArticleIdData = {
    body?: never;
    path: {
        /**
         * Article ID
         */
        articleId: string;
    };
    query?: {
        /**
         * Max messages to return
         */
        limit?: number;
    };
    url: '/agent/conversations/{articleId}';
};

export type GetAgentConversationsByArticleIdErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type GetAgentConversationsByArticleIdError = GetAgentConversationsByArticleIdErrors[keyof GetAgentConversationsByArticleIdErrors];

export type GetAgentConversationsByArticleIdResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: {
            article_id?: string;
            messages?: Array<{
                [key: string]: unknown;
            }>;
            total?: number;
        };
    };
};

export type GetAgentConversationsByArticleIdResponse = GetAgentConversationsByArticleIdResponses[keyof GetAgentConversationsByArticleIdResponses];

export type DeleteAuthAccountData = {
    /**
     * Account deletion confirmation
     */
    body: {
        password?: string;
    };
    path?: never;
    query?: never;
    url: '/auth/account';
};

export type DeleteAuthAccountErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Unauthorized
     */
    401: ResponseSuccessResponse;
};

export type DeleteAuthAccountError = DeleteAuthAccountErrors[keyof DeleteAuthAccountErrors];

export type DeleteAuthAccountResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: {
            message?: string;
        };
    };
};

export type DeleteAuthAccountResponse = DeleteAuthAccountResponses[keyof DeleteAuthAccountResponses];

export type PutAuthAccountData = {
    /**
     * Account update details
     */
    body: DtoUpdateAccountRequest;
    path?: never;
    query?: never;
    url: '/auth/account';
};

export type PutAuthAccountErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Unauthorized
     */
    401: ResponseSuccessResponse;
};

export type PutAuthAccountError = PutAuthAccountErrors[keyof PutAuthAccountErrors];

export type PutAuthAccountResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: {
            message?: string;
        };
    };
};

export type PutAuthAccountResponse = PutAuthAccountResponses[keyof PutAuthAccountResponses];

export type PostAuthLoginData = {
    /**
     * Login credentials
     */
    body: DtoLoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Unauthorized
     */
    401: ResponseSuccessResponse;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: DtoLoginResponse;
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: {
            message?: string;
        };
    };
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type PutAuthPasswordData = {
    /**
     * Password update details
     */
    body: DtoUpdatePasswordRequest;
    path?: never;
    query?: never;
    url: '/auth/password';
};

export type PutAuthPasswordErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Unauthorized
     */
    401: ResponseSuccessResponse;
};

export type PutAuthPasswordError = PutAuthPasswordErrors[keyof PutAuthPasswordErrors];

export type PutAuthPasswordResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: {
            message?: string;
        };
    };
};

export type PutAuthPasswordResponse = PutAuthPasswordResponses[keyof PutAuthPasswordResponses];

export type PostAuthRegisterData = {
    /**
     * Registration details
     */
    body: DtoRegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Conflict
     */
    409: ResponseSuccessResponse;
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
    /**
     * Created
     */
    201: ResponseSuccessResponse & {
        data?: {
            message?: string;
        };
    };
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type GetBlogArticlesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Articles per page
         */
        articlesPerPage?: number;
        /**
         * Filter by tag
         */
        tag?: string;
        /**
         * Filter by status (published/draft)
         */
        status?: string;
        /**
         * Sort field
         */
        sortBy?: string;
        /**
         * Sort order (asc/desc)
         */
        sortOrder?: string;
    };
    url: '/blog/articles';
};

export type GetBlogArticlesErrors = {
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type GetBlogArticlesError = GetBlogArticlesErrors[keyof GetBlogArticlesErrors];

export type GetBlogArticlesResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: DtoArticleListResponse;
    };
};

export type GetBlogArticlesResponse = GetBlogArticlesResponses[keyof GetBlogArticlesResponses];

export type PostBlogArticlesData = {
    /**
     * Create request
     */
    body: DtoCreateArticleRequest;
    path?: never;
    query?: never;
    url: '/blog/articles';
};

export type PostBlogArticlesErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Unauthorized
     */
    401: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PostBlogArticlesError = PostBlogArticlesErrors[keyof PostBlogArticlesErrors];

export type PostBlogArticlesResponses = {
    /**
     * Created
     */
    201: ResponseSuccessResponse & {
        data?: DtoArticleResponse;
    };
};

export type PostBlogArticlesResponse = PostBlogArticlesResponses[keyof PostBlogArticlesResponses];

export type GetBlogArticlesSearchData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Search query
         */
        query: string;
        /**
         * Page number
         */
        page?: number;
        /**
         * Filter by tag
         */
        tag?: string;
        /**
         * Filter by status
         */
        status?: string;
        /**
         * Sort field
         */
        sortBy?: string;
        /**
         * Sort order
         */
        sortOrder?: string;
    };
    url: '/blog/articles/search';
};

export type GetBlogArticlesSearchErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type GetBlogArticlesSearchError = GetBlogArticlesSearchErrors[keyof GetBlogArticlesSearchErrors];

export type GetBlogArticlesSearchResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: DtoArticleListResponse;
    };
};

export type GetBlogArticlesSearchResponse = GetBlogArticlesSearchResponses[keyof GetBlogArticlesSearchResponses];

export type GetBlogArticlesVersionsByVersionIdData = {
    body?: never;
    path: {
        /**
         * Version ID
         */
        versionId: string;
    };
    query?: never;
    url: '/blog/articles/versions/{versionId}';
};

export type GetBlogArticlesVersionsByVersionIdErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Not Found
     */
    404: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type GetBlogArticlesVersionsByVersionIdError = GetBlogArticlesVersionsByVersionIdErrors[keyof GetBlogArticlesVersionsByVersionIdErrors];

export type GetBlogArticlesVersionsByVersionIdResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: DtoArticleVersionResponse;
    };
};

export type GetBlogArticlesVersionsByVersionIdResponse = GetBlogArticlesVersionsByVersionIdResponses[keyof GetBlogArticlesVersionsByVersionIdResponses];

export type DeleteBlogArticlesByIdData = {
    body?: never;
    path: {
        /**
         * Article ID
         */
        id: string;
    };
    query?: never;
    url: '/blog/articles/{id}';
};

export type DeleteBlogArticlesByIdErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Not Found
     */
    404: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type DeleteBlogArticlesByIdError = DeleteBlogArticlesByIdErrors[keyof DeleteBlogArticlesByIdErrors];

export type DeleteBlogArticlesByIdResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: {
            success?: boolean;
        };
    };
};

export type DeleteBlogArticlesByIdResponse = DeleteBlogArticlesByIdResponses[keyof DeleteBlogArticlesByIdResponses];

export type GetBlogArticlesByIdRecommendedData = {
    body?: never;
    path: {
        /**
         * Article ID
         */
        id: string;
    };
    query?: never;
    url: '/blog/articles/{id}/recommended';
};

export type GetBlogArticlesByIdRecommendedErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Not Found
     */
    404: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type GetBlogArticlesByIdRecommendedError = GetBlogArticlesByIdRecommendedErrors[keyof GetBlogArticlesByIdRecommendedErrors];

export type GetBlogArticlesByIdRecommendedResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: Array<DtoArticleResponse>;
    };
};

export type GetBlogArticlesByIdRecommendedResponse = GetBlogArticlesByIdRecommendedResponses[keyof GetBlogArticlesByIdRecommendedResponses];

export type GetBlogArticlesBySlugData = {
    body?: never;
    path: {
        /**
         * Article slug
         */
        slug: string;
    };
    query?: never;
    url: '/blog/articles/{slug}';
};

export type GetBlogArticlesBySlugErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Not Found
     */
    404: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type GetBlogArticlesBySlugError = GetBlogArticlesBySlugErrors[keyof GetBlogArticlesBySlugErrors];

export type GetBlogArticlesBySlugResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: DtoArticleResponse;
    };
};

export type GetBlogArticlesBySlugResponse = GetBlogArticlesBySlugResponses[keyof GetBlogArticlesBySlugResponses];

export type PostBlogArticlesBySlugPublishData = {
    body?: never;
    path: {
        /**
         * Article slug
         */
        slug: string;
    };
    query?: never;
    url: '/blog/articles/{slug}/publish';
};

export type PostBlogArticlesBySlugPublishErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Not Found
     */
    404: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PostBlogArticlesBySlugPublishError = PostBlogArticlesBySlugPublishErrors[keyof PostBlogArticlesBySlugPublishErrors];

export type PostBlogArticlesBySlugPublishResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: DtoArticleResponse;
    };
};

export type PostBlogArticlesBySlugPublishResponse = PostBlogArticlesBySlugPublishResponses[keyof PostBlogArticlesBySlugPublishResponses];

export type PostBlogArticlesBySlugRevertByVersionIdData = {
    body?: never;
    path: {
        /**
         * Article slug
         */
        slug: string;
        /**
         * Version ID to revert to
         */
        versionId: string;
    };
    query?: never;
    url: '/blog/articles/{slug}/revert/{versionId}';
};

export type PostBlogArticlesBySlugRevertByVersionIdErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Not Found
     */
    404: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PostBlogArticlesBySlugRevertByVersionIdError = PostBlogArticlesBySlugRevertByVersionIdErrors[keyof PostBlogArticlesBySlugRevertByVersionIdErrors];

export type PostBlogArticlesBySlugRevertByVersionIdResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: DtoArticleResponse;
    };
};

export type PostBlogArticlesBySlugRevertByVersionIdResponse = PostBlogArticlesBySlugRevertByVersionIdResponses[keyof PostBlogArticlesBySlugRevertByVersionIdResponses];

export type PostBlogArticlesBySlugUnpublishData = {
    body?: never;
    path: {
        /**
         * Article slug
         */
        slug: string;
    };
    query?: never;
    url: '/blog/articles/{slug}/unpublish';
};

export type PostBlogArticlesBySlugUnpublishErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Not Found
     */
    404: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PostBlogArticlesBySlugUnpublishError = PostBlogArticlesBySlugUnpublishErrors[keyof PostBlogArticlesBySlugUnpublishErrors];

export type PostBlogArticlesBySlugUnpublishResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: DtoArticleResponse;
    };
};

export type PostBlogArticlesBySlugUnpublishResponse = PostBlogArticlesBySlugUnpublishResponses[keyof PostBlogArticlesBySlugUnpublishResponses];

export type PostBlogArticlesBySlugUpdateData = {
    /**
     * Update request
     */
    body: DtoUpdateArticleRequest;
    path: {
        /**
         * Article slug
         */
        slug: string;
    };
    query?: never;
    url: '/blog/articles/{slug}/update';
};

export type PostBlogArticlesBySlugUpdateErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Not Found
     */
    404: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PostBlogArticlesBySlugUpdateError = PostBlogArticlesBySlugUpdateErrors[keyof PostBlogArticlesBySlugUpdateErrors];

export type PostBlogArticlesBySlugUpdateResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: DtoArticleResponse;
    };
};

export type PostBlogArticlesBySlugUpdateResponse = PostBlogArticlesBySlugUpdateResponses[keyof PostBlogArticlesBySlugUpdateResponses];

export type GetBlogArticlesBySlugVersionsData = {
    body?: never;
    path: {
        /**
         * Article slug
         */
        slug: string;
    };
    query?: never;
    url: '/blog/articles/{slug}/versions';
};

export type GetBlogArticlesBySlugVersionsErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Not Found
     */
    404: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type GetBlogArticlesBySlugVersionsError = GetBlogArticlesBySlugVersionsErrors[keyof GetBlogArticlesBySlugVersionsErrors];

export type GetBlogArticlesBySlugVersionsResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: DtoArticleVersionListResponse;
    };
};

export type GetBlogArticlesBySlugVersionsResponse = GetBlogArticlesBySlugVersionsResponses[keyof GetBlogArticlesBySlugVersionsResponses];

export type PostBlogGenerateData = {
    /**
     * Generation request
     */
    body: {
        prompt?: string;
        publish?: boolean;
        title?: string;
    };
    path?: never;
    query?: never;
    url: '/blog/generate';
};

export type PostBlogGenerateErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Unauthorized
     */
    401: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PostBlogGenerateError = PostBlogGenerateErrors[keyof PostBlogGenerateErrors];

export type PostBlogGenerateResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: DtoArticleResponse;
    };
};

export type PostBlogGenerateResponse = PostBlogGenerateResponses[keyof PostBlogGenerateResponses];

export type GetBlogTagsPopularData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/blog/tags/popular';
};

export type GetBlogTagsPopularErrors = {
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type GetBlogTagsPopularError = GetBlogTagsPopularErrors[keyof GetBlogTagsPopularErrors];

export type GetBlogTagsPopularResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: {
            tags?: Array<string>;
        };
    };
};

export type GetBlogTagsPopularResponse = GetBlogTagsPopularResponses[keyof GetBlogTagsPopularResponses];

export type PutBlogByIdUpdateData = {
    body?: never;
    path: {
        /**
         * Article ID
         */
        id: string;
    };
    query?: never;
    url: '/blog/{id}/update';
};

export type PutBlogByIdUpdateErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Not Found
     */
    404: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PutBlogByIdUpdateError = PutBlogByIdUpdateErrors[keyof PutBlogByIdUpdateErrors];

export type PutBlogByIdUpdateResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: DtoArticleResponse;
    };
};

export type PutBlogByIdUpdateResponse = PutBlogByIdUpdateResponses[keyof PutBlogByIdUpdateResponses];

export type GetDashboardPagesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Items per page
         */
        perPage?: number;
        /**
         * Filter by published status
         */
        isPublished?: boolean;
    };
    url: '/dashboard/pages';
};

export type GetDashboardPagesErrors = {
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type GetDashboardPagesError = GetDashboardPagesErrors[keyof GetDashboardPagesErrors];

export type GetDashboardPagesResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: DtoPageListResponse;
    };
};

export type GetDashboardPagesResponse = GetDashboardPagesResponses[keyof GetDashboardPagesResponses];

export type PostDashboardPagesData = {
    /**
     * Page details
     */
    body: DtoCreatePageRequest;
    path?: never;
    query?: never;
    url: '/dashboard/pages';
};

export type PostDashboardPagesErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Unauthorized
     */
    401: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PostDashboardPagesError = PostDashboardPagesErrors[keyof PostDashboardPagesErrors];

export type PostDashboardPagesResponses = {
    /**
     * Created
     */
    201: ResponseSuccessResponse & {
        data?: DtoPageResponse;
    };
};

export type PostDashboardPagesResponse = PostDashboardPagesResponses[keyof PostDashboardPagesResponses];

export type DeleteDashboardPagesByIdData = {
    body?: never;
    path: {
        /**
         * Page ID
         */
        id: string;
    };
    query?: never;
    url: '/dashboard/pages/{id}';
};

export type DeleteDashboardPagesByIdErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Not Found
     */
    404: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type DeleteDashboardPagesByIdError = DeleteDashboardPagesByIdErrors[keyof DeleteDashboardPagesByIdErrors];

export type DeleteDashboardPagesByIdResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: {
            success?: boolean;
        };
    };
};

export type DeleteDashboardPagesByIdResponse = DeleteDashboardPagesByIdResponses[keyof DeleteDashboardPagesByIdResponses];

export type GetDashboardPagesByIdData = {
    body?: never;
    path: {
        /**
         * Page ID
         */
        id: string;
    };
    query?: never;
    url: '/dashboard/pages/{id}';
};

export type GetDashboardPagesByIdErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Not Found
     */
    404: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type GetDashboardPagesByIdError = GetDashboardPagesByIdErrors[keyof GetDashboardPagesByIdErrors];

export type GetDashboardPagesByIdResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: DtoPageResponse;
    };
};

export type GetDashboardPagesByIdResponse = GetDashboardPagesByIdResponses[keyof GetDashboardPagesByIdResponses];

export type PutDashboardPagesByIdData = {
    /**
     * Page update details
     */
    body: DtoUpdatePageRequest;
    path: {
        /**
         * Page ID
         */
        id: string;
    };
    query?: never;
    url: '/dashboard/pages/{id}';
};

export type PutDashboardPagesByIdErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Not Found
     */
    404: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PutDashboardPagesByIdError = PutDashboardPagesByIdErrors[keyof PutDashboardPagesByIdErrors];

export type PutDashboardPagesByIdResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: DtoPageResponse;
    };
};

export type PutDashboardPagesByIdResponse = PutDashboardPagesByIdResponses[keyof PutDashboardPagesByIdResponses];

export type GetDashboardSourcesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Items per page
         */
        limit?: number;
    };
    url: '/dashboard/sources';
};

export type GetDashboardSourcesErrors = {
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type GetDashboardSourcesError = GetDashboardSourcesErrors[keyof GetDashboardSourcesErrors];

export type GetDashboardSourcesResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse;
};

export type GetDashboardSourcesResponse = GetDashboardSourcesResponses[keyof GetDashboardSourcesResponses];

export type GetOrganizationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/organizations';
};

export type GetOrganizationsErrors = {
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type GetOrganizationsError = GetOrganizationsErrors[keyof GetOrganizationsErrors];

export type GetOrganizationsResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: Array<DtoOrganizationResponse>;
    };
};

export type GetOrganizationsResponse = GetOrganizationsResponses[keyof GetOrganizationsResponses];

export type PostOrganizationsData = {
    /**
     * Organization details
     */
    body: DtoCreateOrganizationRequest;
    path?: never;
    query?: never;
    url: '/organizations';
};

export type PostOrganizationsErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Unauthorized
     */
    401: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PostOrganizationsError = PostOrganizationsErrors[keyof PostOrganizationsErrors];

export type PostOrganizationsResponses = {
    /**
     * Created
     */
    201: ResponseSuccessResponse & {
        data?: DtoOrganizationResponse;
    };
};

export type PostOrganizationsResponse = PostOrganizationsResponses[keyof PostOrganizationsResponses];

export type PostOrganizationsLeaveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/organizations/leave';
};

export type PostOrganizationsLeaveErrors = {
    /**
     * Unauthorized
     */
    401: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PostOrganizationsLeaveError = PostOrganizationsLeaveErrors[keyof PostOrganizationsLeaveErrors];

export type PostOrganizationsLeaveResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: {
            success?: boolean;
        };
    };
};

export type PostOrganizationsLeaveResponse = PostOrganizationsLeaveResponses[keyof PostOrganizationsLeaveResponses];

export type DeleteOrganizationsByIdData = {
    body?: never;
    path: {
        /**
         * Organization ID
         */
        id: string;
    };
    query?: never;
    url: '/organizations/{id}';
};

export type DeleteOrganizationsByIdErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Not Found
     */
    404: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type DeleteOrganizationsByIdError = DeleteOrganizationsByIdErrors[keyof DeleteOrganizationsByIdErrors];

export type DeleteOrganizationsByIdResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: {
            success?: boolean;
        };
    };
};

export type DeleteOrganizationsByIdResponse = DeleteOrganizationsByIdResponses[keyof DeleteOrganizationsByIdResponses];

export type GetOrganizationsByIdData = {
    body?: never;
    path: {
        /**
         * Organization ID
         */
        id: string;
    };
    query?: never;
    url: '/organizations/{id}';
};

export type GetOrganizationsByIdErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Not Found
     */
    404: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type GetOrganizationsByIdError = GetOrganizationsByIdErrors[keyof GetOrganizationsByIdErrors];

export type GetOrganizationsByIdResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: DtoOrganizationResponse;
    };
};

export type GetOrganizationsByIdResponse = GetOrganizationsByIdResponses[keyof GetOrganizationsByIdResponses];

export type PutOrganizationsByIdData = {
    /**
     * Organization update details
     */
    body: DtoUpdateOrganizationRequest;
    path: {
        /**
         * Organization ID
         */
        id: string;
    };
    query?: never;
    url: '/organizations/{id}';
};

export type PutOrganizationsByIdErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Not Found
     */
    404: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PutOrganizationsByIdError = PutOrganizationsByIdErrors[keyof PutOrganizationsByIdErrors];

export type PutOrganizationsByIdResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: DtoOrganizationResponse;
    };
};

export type PutOrganizationsByIdResponse = PutOrganizationsByIdResponses[keyof PutOrganizationsByIdResponses];

export type PostOrganizationsByIdJoinData = {
    body?: never;
    path: {
        /**
         * Organization ID
         */
        id: string;
    };
    query?: never;
    url: '/organizations/{id}/join';
};

export type PostOrganizationsByIdJoinErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Unauthorized
     */
    401: ResponseSuccessResponse;
    /**
     * Not Found
     */
    404: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PostOrganizationsByIdJoinError = PostOrganizationsByIdJoinErrors[keyof PostOrganizationsByIdJoinErrors];

export type PostOrganizationsByIdJoinResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: {
            success?: boolean;
        };
    };
};

export type PostOrganizationsByIdJoinResponse = PostOrganizationsByIdJoinResponses[keyof PostOrganizationsByIdJoinResponses];

export type GetPagesBySlugData = {
    body?: never;
    path: {
        /**
         * Page slug
         */
        slug: string;
    };
    query?: never;
    url: '/pages/{slug}';
};

export type GetPagesBySlugErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Not Found
     */
    404: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type GetPagesBySlugError = GetPagesBySlugErrors[keyof GetPagesBySlugErrors];

export type GetPagesBySlugResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: DtoPageResponse;
    };
};

export type GetPagesBySlugResponse = GetPagesBySlugResponses[keyof GetPagesBySlugResponses];

export type GetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/profile';
};

export type GetProfileErrors = {
    /**
     * Unauthorized
     */
    401: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type GetProfileError = GetProfileErrors[keyof GetProfileErrors];

export type GetProfileResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse;
};

export type GetProfileResponse = GetProfileResponses[keyof GetProfileResponses];

export type PutProfileData = {
    /**
     * Profile update details
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/profile';
};

export type PutProfileErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Unauthorized
     */
    401: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PutProfileError = PutProfileErrors[keyof PutProfileErrors];

export type PutProfileResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse;
};

export type PutProfileResponse = PutProfileResponses[keyof PutProfileResponses];

export type GetProfilePublicData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/profile/public';
};

export type GetProfilePublicErrors = {
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type GetProfilePublicError = GetProfilePublicErrors[keyof GetProfilePublicErrors];

export type GetProfilePublicResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse;
};

export type GetProfilePublicResponse = GetProfilePublicResponses[keyof GetProfilePublicResponses];

export type GetProfileSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/profile/settings';
};

export type GetProfileSettingsErrors = {
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type GetProfileSettingsError = GetProfileSettingsErrors[keyof GetProfileSettingsErrors];

export type GetProfileSettingsResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse;
};

export type GetProfileSettingsResponse = GetProfileSettingsResponses[keyof GetProfileSettingsResponses];

export type PutProfileSettingsData = {
    /**
     * Site settings update
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/profile/settings';
};

export type PutProfileSettingsErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Unauthorized
     */
    401: ResponseSuccessResponse;
    /**
     * Forbidden
     */
    403: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PutProfileSettingsError = PutProfileSettingsErrors[keyof PutProfileSettingsErrors];

export type PutProfileSettingsResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse;
};

export type PutProfileSettingsResponse = PutProfileSettingsResponses[keyof PutProfileSettingsResponses];

export type GetProjectsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Items per page
         */
        perPage?: number;
    };
    url: '/projects';
};

export type GetProjectsErrors = {
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type GetProjectsError = GetProjectsErrors[keyof GetProjectsErrors];

export type GetProjectsResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: DtoProjectListResponse;
    };
};

export type GetProjectsResponse = GetProjectsResponses[keyof GetProjectsResponses];

export type PostProjectsData = {
    /**
     * Project details
     */
    body: DtoCreateProjectRequest;
    path?: never;
    query?: never;
    url: '/projects';
};

export type PostProjectsErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Unauthorized
     */
    401: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PostProjectsError = PostProjectsErrors[keyof PostProjectsErrors];

export type PostProjectsResponses = {
    /**
     * Created
     */
    201: ResponseSuccessResponse & {
        data?: DtoProjectResponse;
    };
};

export type PostProjectsResponse = PostProjectsResponses[keyof PostProjectsResponses];

export type DeleteProjectsByIdData = {
    body?: never;
    path: {
        /**
         * Project ID
         */
        id: string;
    };
    query?: never;
    url: '/projects/{id}';
};

export type DeleteProjectsByIdErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Unauthorized
     */
    401: ResponseSuccessResponse;
    /**
     * Not Found
     */
    404: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type DeleteProjectsByIdError = DeleteProjectsByIdErrors[keyof DeleteProjectsByIdErrors];

export type DeleteProjectsByIdResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: {
            success?: boolean;
        };
    };
};

export type DeleteProjectsByIdResponse = DeleteProjectsByIdResponses[keyof DeleteProjectsByIdResponses];

export type GetProjectsByIdData = {
    body?: never;
    path: {
        /**
         * Project ID
         */
        id: string;
    };
    query?: never;
    url: '/projects/{id}';
};

export type GetProjectsByIdErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Not Found
     */
    404: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type GetProjectsByIdError = GetProjectsByIdErrors[keyof GetProjectsByIdErrors];

export type GetProjectsByIdResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: DtoProjectResponse;
    };
};

export type GetProjectsByIdResponse = GetProjectsByIdResponses[keyof GetProjectsByIdResponses];

export type PutProjectsByIdData = {
    /**
     * Project update details
     */
    body: DtoUpdateProjectRequest;
    path: {
        /**
         * Project ID
         */
        id: string;
    };
    query?: never;
    url: '/projects/{id}';
};

export type PutProjectsByIdErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Not Found
     */
    404: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PutProjectsByIdError = PutProjectsByIdErrors[keyof PutProjectsByIdErrors];

export type PutProjectsByIdResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: DtoProjectResponse;
    };
};

export type PutProjectsByIdResponse = PutProjectsByIdResponses[keyof PutProjectsByIdResponses];

export type PostSourcesData = {
    /**
     * Source details
     */
    body: DtoCreateSourceRequest;
    path?: never;
    query?: never;
    url: '/sources';
};

export type PostSourcesErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Unauthorized
     */
    401: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PostSourcesError = PostSourcesErrors[keyof PostSourcesErrors];

export type PostSourcesResponses = {
    /**
     * Created
     */
    201: ResponseSuccessResponse & {
        data?: DtoSourceResponse;
    };
};

export type PostSourcesResponse = PostSourcesResponses[keyof PostSourcesResponses];

export type GetSourcesArticleByArticleIdData = {
    body?: never;
    path: {
        /**
         * Article ID
         */
        articleId: string;
    };
    query?: never;
    url: '/sources/article/{articleId}';
};

export type GetSourcesArticleByArticleIdErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type GetSourcesArticleByArticleIdError = GetSourcesArticleByArticleIdErrors[keyof GetSourcesArticleByArticleIdErrors];

export type GetSourcesArticleByArticleIdResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: {
            sources?: Array<DtoSourceResponse>;
        };
    };
};

export type GetSourcesArticleByArticleIdResponse = GetSourcesArticleByArticleIdResponses[keyof GetSourcesArticleByArticleIdResponses];

export type GetSourcesArticleByArticleIdSearchData = {
    body?: never;
    path: {
        /**
         * Article ID
         */
        articleId: string;
    };
    query: {
        /**
         * Search query
         */
        q: string;
        /**
         * Max results
         */
        limit?: number;
    };
    url: '/sources/article/{articleId}/search';
};

export type GetSourcesArticleByArticleIdSearchErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type GetSourcesArticleByArticleIdSearchError = GetSourcesArticleByArticleIdSearchErrors[keyof GetSourcesArticleByArticleIdSearchErrors];

export type GetSourcesArticleByArticleIdSearchResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: {
            query?: string;
            sources?: Array<DtoSourceResponse>;
        };
    };
};

export type GetSourcesArticleByArticleIdSearchResponse = GetSourcesArticleByArticleIdSearchResponses[keyof GetSourcesArticleByArticleIdSearchResponses];

export type PostSourcesScrapeData = {
    /**
     * Scrape request
     */
    body: {
        article_id?: string;
        url?: string;
    };
    path?: never;
    query?: never;
    url: '/sources/scrape';
};

export type PostSourcesScrapeErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Unauthorized
     */
    401: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PostSourcesScrapeError = PostSourcesScrapeErrors[keyof PostSourcesScrapeErrors];

export type PostSourcesScrapeResponses = {
    /**
     * Created
     */
    201: ResponseSuccessResponse & {
        data?: DtoSourceResponse;
    };
};

export type PostSourcesScrapeResponse = PostSourcesScrapeResponses[keyof PostSourcesScrapeResponses];

export type DeleteSourcesBySourceIdData = {
    body?: never;
    path: {
        /**
         * Source ID
         */
        sourceId: string;
    };
    query?: never;
    url: '/sources/{sourceId}';
};

export type DeleteSourcesBySourceIdErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Not Found
     */
    404: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type DeleteSourcesBySourceIdError = DeleteSourcesBySourceIdErrors[keyof DeleteSourcesBySourceIdErrors];

export type DeleteSourcesBySourceIdResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: {
            success?: boolean;
        };
    };
};

export type DeleteSourcesBySourceIdResponse = DeleteSourcesBySourceIdResponses[keyof DeleteSourcesBySourceIdResponses];

export type GetSourcesBySourceIdData = {
    body?: never;
    path: {
        /**
         * Source ID
         */
        sourceId: string;
    };
    query?: never;
    url: '/sources/{sourceId}';
};

export type GetSourcesBySourceIdErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Not Found
     */
    404: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type GetSourcesBySourceIdError = GetSourcesBySourceIdErrors[keyof GetSourcesBySourceIdErrors];

export type GetSourcesBySourceIdResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: DtoSourceResponse;
    };
};

export type GetSourcesBySourceIdResponse = GetSourcesBySourceIdResponses[keyof GetSourcesBySourceIdResponses];

export type PutSourcesBySourceIdData = {
    /**
     * Source update details
     */
    body: DtoUpdateSourceRequest;
    path: {
        /**
         * Source ID
         */
        sourceId: string;
    };
    query?: never;
    url: '/sources/{sourceId}';
};

export type PutSourcesBySourceIdErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Not Found
     */
    404: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PutSourcesBySourceIdError = PutSourcesBySourceIdErrors[keyof PutSourcesBySourceIdErrors];

export type PutSourcesBySourceIdResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: DtoSourceResponse;
    };
};

export type PutSourcesBySourceIdResponse = PutSourcesBySourceIdResponses[keyof PutSourcesBySourceIdResponses];

export type GetStorageFilesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * File prefix filter
         */
        prefix?: string;
    };
    url: '/storage/files';
};

export type GetStorageFilesErrors = {
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type GetStorageFilesError = GetStorageFilesErrors[keyof GetStorageFilesErrors];

export type GetStorageFilesResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse;
};

export type GetStorageFilesResponse = GetStorageFilesResponses[keyof GetStorageFilesResponses];

export type PostStorageFoldersData = {
    /**
     * Folder path
     */
    body: StorageCreateFolderRequest;
    path?: never;
    query?: never;
    url: '/storage/folders';
};

export type PostStorageFoldersErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Unauthorized
     */
    401: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PostStorageFoldersError = PostStorageFoldersErrors[keyof PostStorageFoldersErrors];

export type PostStorageFoldersResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: {
            success?: boolean;
        };
    };
};

export type PostStorageFoldersResponse = PostStorageFoldersResponses[keyof PostStorageFoldersResponses];

export type PutStorageFoldersData = {
    /**
     * Old and new folder paths
     */
    body: StorageUpdateFolderRequest;
    path?: never;
    query?: never;
    url: '/storage/folders';
};

export type PutStorageFoldersErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Unauthorized
     */
    401: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PutStorageFoldersError = PutStorageFoldersErrors[keyof PutStorageFoldersErrors];

export type PutStorageFoldersResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: {
            success?: boolean;
        };
    };
};

export type PutStorageFoldersResponse = PutStorageFoldersResponses[keyof PutStorageFoldersResponses];

export type PostStorageUploadData = {
    body: {
        /**
         * File key/path
         */
        key: string;
        /**
         * File to upload
         */
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/storage/upload';
};

export type PostStorageUploadErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Unauthorized
     */
    401: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type PostStorageUploadError = PostStorageUploadErrors[keyof PostStorageUploadErrors];

export type PostStorageUploadResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: {
            key?: string;
            success?: boolean;
            url?: string;
        };
    };
};

export type PostStorageUploadResponse = PostStorageUploadResponses[keyof PostStorageUploadResponses];

export type DeleteStorageByKeyData = {
    body?: never;
    path: {
        /**
         * File key/path
         */
        key: string;
    };
    query?: never;
    url: '/storage/{key}';
};

export type DeleteStorageByKeyErrors = {
    /**
     * Bad Request
     */
    400: ResponseSuccessResponse;
    /**
     * Unauthorized
     */
    401: ResponseSuccessResponse;
    /**
     * Internal Server Error
     */
    500: ResponseSuccessResponse;
};

export type DeleteStorageByKeyError = DeleteStorageByKeyErrors[keyof DeleteStorageByKeyErrors];

export type DeleteStorageByKeyResponses = {
    /**
     * OK
     */
    200: ResponseSuccessResponse & {
        data?: {
            success?: boolean;
        };
    };
};

export type DeleteStorageByKeyResponse = DeleteStorageByKeyResponses[keyof DeleteStorageByKeyResponses];
