// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AuthErrorResponse = {
    error: string;
    code: string;
    details?: {
        [key: string]: string;
    } | null;
};

export type DeleteAccountRequest = {
    /**
     * Password UTF-8 encoding must not exceed 72 bytes.
     */
    password: string;
};

export type HealthResponse = {
    status: string;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type LoginResponse = {
    token: string;
    user: UserResponse;
};

export type MessageResponse = {
    message: string;
};

export type RegisterRequest = {
    name: string;
    email: string;
    /**
     * Password UTF-8 encoding must not exceed 72 bytes.
     */
    password: string;
};

export type RootResponse = {
    message: string;
};

export type SuccessResponseLoginResponse = {
    data: {
        token: string;
        user: UserResponse;
    };
};

export type SuccessResponseMessageResponse = {
    data: {
        message: string;
    };
};

export type UpdateAccountRequest = {
    name: string;
    email: string;
};

export type UpdatePasswordRequest = {
    /**
     * Password UTF-8 encoding must not exceed 72 bytes.
     */
    currentPassword: string;
    /**
     * Password UTF-8 encoding must not exceed 72 bytes.
     */
    newPassword: string;
};

export type UserResponse = {
    id: string;
    name: string;
    email: string;
    role: string;
};

export type RootStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootStatusResponses = {
    200: RootResponse;
};

export type RootStatusResponse = RootStatusResponses[keyof RootStatusResponses];

export type AuthDeleteAccountData = {
    body: DeleteAccountRequest;
    path?: never;
    query?: never;
    url: '/auth/account';
};

export type AuthDeleteAccountErrors = {
    400: AuthErrorResponse;
    401: AuthErrorResponse;
    404: AuthErrorResponse;
    500: AuthErrorResponse;
};

export type AuthDeleteAccountError = AuthDeleteAccountErrors[keyof AuthDeleteAccountErrors];

export type AuthDeleteAccountResponses = {
    200: SuccessResponseMessageResponse;
};

export type AuthDeleteAccountResponse = AuthDeleteAccountResponses[keyof AuthDeleteAccountResponses];

export type AuthUpdateAccountData = {
    body: UpdateAccountRequest;
    path?: never;
    query?: never;
    url: '/auth/account';
};

export type AuthUpdateAccountErrors = {
    400: AuthErrorResponse;
    401: AuthErrorResponse;
    404: AuthErrorResponse;
    409: AuthErrorResponse;
    500: AuthErrorResponse;
};

export type AuthUpdateAccountError = AuthUpdateAccountErrors[keyof AuthUpdateAccountErrors];

export type AuthUpdateAccountResponses = {
    200: SuccessResponseMessageResponse;
};

export type AuthUpdateAccountResponse = AuthUpdateAccountResponses[keyof AuthUpdateAccountResponses];

export type AuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthLoginErrors = {
    400: AuthErrorResponse;
    401: AuthErrorResponse;
    500: AuthErrorResponse;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
    200: SuccessResponseLoginResponse;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthLogoutResponses = {
    200: SuccessResponseMessageResponse;
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthUpdatePasswordData = {
    body: UpdatePasswordRequest;
    path?: never;
    query?: never;
    url: '/auth/password';
};

export type AuthUpdatePasswordErrors = {
    400: AuthErrorResponse;
    401: AuthErrorResponse;
    404: AuthErrorResponse;
    500: AuthErrorResponse;
};

export type AuthUpdatePasswordError = AuthUpdatePasswordErrors[keyof AuthUpdatePasswordErrors];

export type AuthUpdatePasswordResponses = {
    200: SuccessResponseMessageResponse;
};

export type AuthUpdatePasswordResponse = AuthUpdatePasswordResponses[keyof AuthUpdatePasswordResponses];

export type AuthRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthRegisterErrors = {
    400: AuthErrorResponse;
    409: AuthErrorResponse;
    500: AuthErrorResponse;
};

export type AuthRegisterError = AuthRegisterErrors[keyof AuthRegisterErrors];

export type AuthRegisterResponses = {
    201: SuccessResponseMessageResponse;
};

export type AuthRegisterResponse = AuthRegisterResponses[keyof AuthRegisterResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckResponses = {
    200: HealthResponse;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type ConnectWebSocketData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/websocket';
};

export type ConnectWebSocketErrors = {
    /**
     * Invalid WebSocket upgrade headers
     */
    400: unknown;
    /**
     * Connection cannot be upgraded
     */
    426: unknown;
};
