# Python server

services:
  # Flask Application Service
  app:
    build:
      context: . 
      dockerfile: Dockerfile  
    container_name: blog-flask-server  
    env_file: .env  
    ports:
      - "5000:5000" 
    volumes:
      - ./app:/code/app
    command: gunicorn -w 4 -b 0.0.0.0:5000 app.wsgi:app 
    networks:
      - blog_app_shared_network

  # Celery Workers Service
  celery:
    build:
      context: .  
      dockerfile: Dockerfile
    container_name: blog-celery-worker
    env_file: .env  
    command: celery -A app.app.celery worker --loglevel=info
    networks:
      - blog_app_shared_network
    
networks:
  blog_app_shared_network:
    name: BlogAppSharedNetwork
