# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: blog
    build: .
    command: gunicorn -b 0.0.0.0:5000 blog.wsgi:app
    env_file:
      - ./.env
    environment:
      - DATABASE_URI=${DATABASE_URI:-postgresql://postgres:postgrespass@postgres:5432/myapp}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-redis://:redispass@redis:6379/0}
      - CELERY_RESULT_BACKEND_URL=${CELERY_RESULT_BACKEND_URL:-redis://:redispass@redis:6379/1}
    volumes:
      - ./app:/code/app
      - ./db/:/db/
    ports:
      - "5000:5000"
  celery:
    image: blog-celery
    command: "celery worker -A blog.celery_app:app"
    env_file:
      - ./.env
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-redis://:redispass@redis:6379/0}
      - CELERY_RESULT__URL=${CELERY_RESULT_BACKEND_URL:-redis://:redispass@redis:6379/1}
