# Python server

services:
  # Flask Application Service
  app:
    build:
      context: .  # Current directory
      dockerfile: Dockerfile  # Specify the Dockerfile
    container_name: blog_flask_app  # Give your container a name
    env_file: .env  # Load environment variables from .env file
    ports:
      - "5000:5000"  # Map port 5000 to host
    volumes:
      - ./app:/code/app  # Optional: mount your app directory for development
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app # Command to run the app

  # Celery Worker Service (if needed)
  celery:
    build:
      context: .  # Current directory
      dockerfile: Dockerfile
    container_name: blog_celery_worker
    env_file: .env  # Load environment variables from .env file
    command: celery worker -A app.celery_app:app
