package models

import (
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/pgvector/pgvector-go"
	"gorm.io/datatypes"
)

// DataSource is the GORM model for data sources (preferred websites to crawl)
type DataSource struct {
	ID               uuid.UUID      `json:"id" gorm:"type:uuid;primaryKey;default:uuid_generate_v4()"`
	OrganizationID   *uuid.UUID     `json:"organization_id" gorm:"type:uuid;index"`
	UserID           *uuid.UUID     `json:"user_id" gorm:"type:uuid;index"`
	Name             string         `json:"name" gorm:"type:varchar(255);not null"`
	URL              string         `json:"url" gorm:"type:text;not null"`
	FeedURL          *string        `json:"feed_url" gorm:"type:text"`
	SourceType       string         `json:"source_type" gorm:"type:varchar(50);default:blog"`
	CrawlFrequency   string         `json:"crawl_frequency" gorm:"type:varchar(50);default:daily"`
	IsEnabled        bool           `json:"is_enabled" gorm:"default:true"`
	IsDiscovered     bool           `json:"is_discovered" gorm:"default:false"`
	DiscoveredFromID *uuid.UUID     `json:"discovered_from_id" gorm:"type:uuid"`
	LastCrawledAt    *time.Time     `json:"last_crawled_at"`
	NextCrawlAt      *time.Time     `json:"next_crawl_at"`
	CrawlStatus      string         `json:"crawl_status" gorm:"type:varchar(50);default:pending"`
	ErrorMessage     *string        `json:"error_message" gorm:"type:text"`
	ContentCount     int            `json:"content_count" gorm:"default:0"`
	SubscriberCount  int            `json:"subscriber_count" gorm:"default:1"`
	MetaData         datatypes.JSON `json:"meta_data" gorm:"type:jsonb;default:'{}'"`
	CreatedAt        time.Time      `json:"created_at" gorm:"autoCreateTime"`
	UpdatedAt        time.Time      `json:"updated_at" gorm:"autoUpdateTime"`
}

func (DataSource) TableName() string {
	return "data_source"
}

// CrawledContent is the GORM model for crawled content from data sources
type CrawledContent struct {
	ID           uuid.UUID       `json:"id" gorm:"type:uuid;primaryKey;default:uuid_generate_v4()"`
	DataSourceID uuid.UUID       `json:"data_source_id" gorm:"type:uuid;not null;index"`
	URL          string          `json:"url" gorm:"type:text;not null"`
	Title        *string         `json:"title" gorm:"type:varchar(500)"`
	Content      string          `json:"content" gorm:"type:text;not null"`
	Summary      *string         `json:"summary" gorm:"type:text"`
	Author       *string         `json:"author" gorm:"type:varchar(255)"`
	PublishedAt  *time.Time      `json:"published_at"`
	Embedding    pgvector.Vector `json:"embedding" gorm:"type:vector(1536)"`
	MetaData     datatypes.JSON  `json:"meta_data" gorm:"type:jsonb;default:'{}'"`
	CreatedAt    time.Time       `json:"created_at" gorm:"autoCreateTime"`

	// Relationships
	DataSource DataSource `json:"data_source" gorm:"foreignKey:DataSourceID"`
}

func (CrawledContent) TableName() string {
	return "crawled_content"
}

// InsightTopic is the GORM model for insight topics
type InsightTopic struct {
	ID              uuid.UUID       `json:"id" gorm:"type:uuid;primaryKey;default:uuid_generate_v4()"`
	OrganizationID  *uuid.UUID      `json:"organization_id" gorm:"type:uuid;index"`
	Name            string          `json:"name" gorm:"type:varchar(255);not null"`
	Description     *string         `json:"description" gorm:"type:text"`
	Keywords        datatypes.JSON  `json:"keywords" gorm:"type:jsonb;default:'[]'"`
	Embedding       pgvector.Vector `json:"embedding" gorm:"type:vector(1536)"`
	IsAutoGenerated bool            `json:"is_auto_generated" gorm:"default:false"`
	ContentCount    int             `json:"content_count" gorm:"default:0"`
	LastInsightAt   *time.Time      `json:"last_insight_at"`
	Color           *string         `json:"color" gorm:"type:varchar(20)"`
	Icon            *string         `json:"icon" gorm:"type:varchar(50)"`
	CreatedAt       time.Time       `json:"created_at" gorm:"autoCreateTime"`
	UpdatedAt       time.Time       `json:"updated_at" gorm:"autoUpdateTime"`
}

func (InsightTopic) TableName() string {
	return "insight_topic"
}

// ContentTopicMatch is the GORM model for content-topic relationships
type ContentTopicMatch struct {
	ID              uuid.UUID `json:"id" gorm:"type:uuid;primaryKey;default:uuid_generate_v4()"`
	ContentID       uuid.UUID `json:"content_id" gorm:"type:uuid;not null;index"`
	TopicID         uuid.UUID `json:"topic_id" gorm:"type:uuid;not null;index"`
	SimilarityScore float64   `json:"similarity_score" gorm:"not null"`
	IsPrimary       bool      `json:"is_primary" gorm:"default:false"`
	CreatedAt       time.Time `json:"created_at" gorm:"autoCreateTime"`

	// Relationships
	Content CrawledContent `json:"content" gorm:"foreignKey:ContentID"`
	Topic   InsightTopic   `json:"topic" gorm:"foreignKey:TopicID"`
}

func (ContentTopicMatch) TableName() string {
	return "content_topic_match"
}

// Insight is the GORM model for generated insights
type Insight struct {
	ID               uuid.UUID       `json:"id" gorm:"type:uuid;primaryKey;default:uuid_generate_v4()"`
	OrganizationID   *uuid.UUID      `json:"organization_id" gorm:"type:uuid;index"`
	TopicID          *uuid.UUID      `json:"topic_id" gorm:"type:uuid;index"`
	Title            string          `json:"title" gorm:"type:varchar(500);not null"`
	Summary          string          `json:"summary" gorm:"type:text;not null"`
	Content          *string         `json:"content" gorm:"type:text"`
	KeyPoints        datatypes.JSON  `json:"key_points" gorm:"type:jsonb;default:'[]'"`
	SourceContentIDs pq.StringArray  `json:"source_content_ids" gorm:"type:uuid[];default:'{}'"`
	Embedding        pgvector.Vector `json:"embedding" gorm:"type:vector(1536)"`
	GeneratedAt      time.Time       `json:"generated_at" gorm:"autoCreateTime"`
	PeriodStart      *time.Time      `json:"period_start"`
	PeriodEnd        *time.Time      `json:"period_end"`
	IsRead           bool            `json:"is_read" gorm:"default:false"`
	IsPinned         bool            `json:"is_pinned" gorm:"default:false"`
	IsUsedInArticle  bool            `json:"is_used_in_article" gorm:"default:false"`
	MetaData         datatypes.JSON  `json:"meta_data" gorm:"type:jsonb;default:'{}'"`

	// Relationships
	Topic *InsightTopic `json:"topic" gorm:"foreignKey:TopicID"`
}

func (Insight) TableName() string {
	return "insight"
}

// UserInsightStatus is the GORM model for per-user insight tracking
type UserInsightStatus struct {
	ID              uuid.UUID  `json:"id" gorm:"type:uuid;primaryKey;default:uuid_generate_v4()"`
	UserID          uuid.UUID  `json:"user_id" gorm:"type:uuid;not null;index"`
	InsightID       uuid.UUID  `json:"insight_id" gorm:"type:uuid;not null;index"`
	IsRead          bool       `json:"is_read" gorm:"default:false"`
	IsPinned        bool       `json:"is_pinned" gorm:"default:false"`
	IsUsedInArticle bool       `json:"is_used_in_article" gorm:"default:false"`
	ReadAt          *time.Time `json:"read_at"`
	CreatedAt       time.Time  `json:"created_at" gorm:"autoCreateTime"`

	// Relationships
	Insight *Insight `json:"insight" gorm:"foreignKey:InsightID"`
}

func (UserInsightStatus) TableName() string {
	return "user_insight_status"
}
