/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as NotFoundImport } from './routes/not-found'
import { Route as LoginImport } from './routes/login'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as ContactImport } from './routes/contact'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as BlogIndexImport } from './routes/blog/index'
import { Route as DashboardUploadsImport } from './routes/dashboard/uploads'
import { Route as DashboardSecurityImport } from './routes/dashboard/security'
import { Route as DashboardGeneralImport } from './routes/dashboard/general'
import { Route as BlogBlogSlugImport } from './routes/blog/$blogSlug'
import { Route as DashboardBlogIndexImport } from './routes/dashboard/blog/index'
import { Route as DashboardBlogNewImport } from './routes/dashboard/blog/new'
import { Route as DashboardBlogEditBlogIdImport } from './routes/dashboard/blog/edit.$blogId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const NotFoundRoute = NotFoundImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)

const BlogIndexRoute = BlogIndexImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardUploadsRoute = DashboardUploadsImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardSecurityRoute = DashboardSecurityImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardGeneralRoute = DashboardGeneralImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => DashboardRoute,
} as any)

const BlogBlogSlugRoute = BlogBlogSlugImport.update({
  id: '/blog/$blogSlug',
  path: '/blog/$blogSlug',
  getParentRoute: () => rootRoute,
} as any)

const DashboardBlogIndexRoute = DashboardBlogIndexImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardBlogNewRoute = DashboardBlogNewImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardBlogEditBlogIdRoute = DashboardBlogEditBlogIdImport.update({
  id: '/blog/edit/$blogId',
  path: '/blog/edit/$blogId',
  getParentRoute: () => DashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/blog/$blogSlug': {
      id: '/blog/$blogSlug'
      path: '/blog/$blogSlug'
      fullPath: '/blog/$blogSlug'
      preLoaderRoute: typeof BlogBlogSlugImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/general': {
      id: '/dashboard/general'
      path: '/general'
      fullPath: '/dashboard/general'
      preLoaderRoute: typeof DashboardGeneralImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/security': {
      id: '/dashboard/security'
      path: '/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof DashboardSecurityImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/uploads': {
      id: '/dashboard/uploads'
      path: '/uploads'
      fullPath: '/dashboard/uploads'
      preLoaderRoute: typeof DashboardUploadsImport
      parentRoute: typeof DashboardImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/blog/new': {
      id: '/dashboard/blog/new'
      path: '/blog/new'
      fullPath: '/dashboard/blog/new'
      preLoaderRoute: typeof DashboardBlogNewImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/blog/': {
      id: '/dashboard/blog/'
      path: '/blog'
      fullPath: '/dashboard/blog'
      preLoaderRoute: typeof DashboardBlogIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/blog/edit/$blogId': {
      id: '/dashboard/blog/edit/$blogId'
      path: '/blog/edit/$blogId'
      fullPath: '/dashboard/blog/edit/$blogId'
      preLoaderRoute: typeof DashboardBlogEditBlogIdImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

interface DashboardRouteChildren {
  DashboardGeneralRoute: typeof DashboardGeneralRoute
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardUploadsRoute: typeof DashboardUploadsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBlogNewRoute: typeof DashboardBlogNewRoute
  DashboardBlogIndexRoute: typeof DashboardBlogIndexRoute
  DashboardBlogEditBlogIdRoute: typeof DashboardBlogEditBlogIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardGeneralRoute: DashboardGeneralRoute,
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardUploadsRoute: DashboardUploadsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBlogNewRoute: DashboardBlogNewRoute,
  DashboardBlogIndexRoute: DashboardBlogIndexRoute,
  DashboardBlogEditBlogIdRoute: DashboardBlogEditBlogIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/signup': typeof SignupRoute
  '/blog/$blogSlug': typeof BlogBlogSlugRoute
  '/dashboard/general': typeof DashboardGeneralRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/uploads': typeof DashboardUploadsRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/blog/new': typeof DashboardBlogNewRoute
  '/dashboard/blog': typeof DashboardBlogIndexRoute
  '/dashboard/blog/edit/$blogId': typeof DashboardBlogEditBlogIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/signup': typeof SignupRoute
  '/blog/$blogSlug': typeof BlogBlogSlugRoute
  '/dashboard/general': typeof DashboardGeneralRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/uploads': typeof DashboardUploadsRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/blog/new': typeof DashboardBlogNewRoute
  '/dashboard/blog': typeof DashboardBlogIndexRoute
  '/dashboard/blog/edit/$blogId': typeof DashboardBlogEditBlogIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/signup': typeof SignupRoute
  '/blog/$blogSlug': typeof BlogBlogSlugRoute
  '/dashboard/general': typeof DashboardGeneralRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/uploads': typeof DashboardUploadsRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/blog/new': typeof DashboardBlogNewRoute
  '/dashboard/blog/': typeof DashboardBlogIndexRoute
  '/dashboard/blog/edit/$blogId': typeof DashboardBlogEditBlogIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/not-found'
    | '/signup'
    | '/blog/$blogSlug'
    | '/dashboard/general'
    | '/dashboard/security'
    | '/dashboard/uploads'
    | '/blog'
    | '/dashboard/'
    | '/dashboard/blog/new'
    | '/dashboard/blog'
    | '/dashboard/blog/edit/$blogId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/not-found'
    | '/signup'
    | '/blog/$blogSlug'
    | '/dashboard/general'
    | '/dashboard/security'
    | '/dashboard/uploads'
    | '/blog'
    | '/dashboard'
    | '/dashboard/blog/new'
    | '/dashboard/blog'
    | '/dashboard/blog/edit/$blogId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/not-found'
    | '/signup'
    | '/blog/$blogSlug'
    | '/dashboard/general'
    | '/dashboard/security'
    | '/dashboard/uploads'
    | '/blog/'
    | '/dashboard/'
    | '/dashboard/blog/new'
    | '/dashboard/blog/'
    | '/dashboard/blog/edit/$blogId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotFoundRoute: typeof NotFoundRoute
  SignupRoute: typeof SignupRoute
  BlogBlogSlugRoute: typeof BlogBlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  NotFoundRoute: NotFoundRoute,
  SignupRoute: SignupRoute,
  BlogBlogSlugRoute: BlogBlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/contact",
        "/dashboard",
        "/login",
        "/not-found",
        "/signup",
        "/blog/$blogSlug",
        "/blog/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx",
      "children": [
        "/dashboard/general",
        "/dashboard/security",
        "/dashboard/uploads",
        "/dashboard/",
        "/dashboard/blog/new",
        "/dashboard/blog/",
        "/dashboard/blog/edit/$blogId"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/not-found": {
      "filePath": "not-found.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/blog/$blogSlug": {
      "filePath": "blog/$blogSlug.tsx"
    },
    "/dashboard/general": {
      "filePath": "dashboard/general.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/security": {
      "filePath": "dashboard/security.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/uploads": {
      "filePath": "dashboard/uploads.tsx",
      "parent": "/dashboard"
    },
    "/blog/": {
      "filePath": "blog/index.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/blog/new": {
      "filePath": "dashboard/blog/new.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/blog/": {
      "filePath": "dashboard/blog/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/blog/edit/$blogId": {
      "filePath": "dashboard/blog/edit.$blogId.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
