/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NotFoundImport } from './routes/not-found'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as PublicLayoutImport } from './routes/_publicLayout'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as PublicLayoutIndexImport } from './routes/_publicLayout/index'
import { Route as DashboardUploadsImport } from './routes/dashboard/uploads'
import { Route as DashboardSettingsImport } from './routes/dashboard/settings'
import { Route as DashboardSecurityImport } from './routes/dashboard/security'
import { Route as PublicLayoutSignupImport } from './routes/_publicLayout/signup'
import { Route as PublicLayoutLoginImport } from './routes/_publicLayout/login'
import { Route as PublicLayoutAboutImport } from './routes/_publicLayout/about'
import { Route as DashboardProjectsIndexImport } from './routes/dashboard/projects/index'
import { Route as DashboardPagesIndexImport } from './routes/dashboard/pages/index'
import { Route as DashboardBlogIndexImport } from './routes/dashboard/blog/index'
import { Route as PublicLayoutProjectsIndexImport } from './routes/_publicLayout/projects/index'
import { Route as PublicLayoutBlogIndexImport } from './routes/_publicLayout/blog/index'
import { Route as DashboardProjectsNewImport } from './routes/dashboard/projects/new'
import { Route as DashboardPagesNewImport } from './routes/dashboard/pages/new'
import { Route as DashboardBlogNewImport } from './routes/dashboard/blog/new'
import { Route as PublicLayoutProjectsProjectIdImport } from './routes/_publicLayout/projects/$projectId'
import { Route as PublicLayoutBlogBlogSlugImport } from './routes/_publicLayout/blog/$blogSlug'
import { Route as DashboardProjectsEditProjectIdImport } from './routes/dashboard/projects/edit.$projectId'
import { Route as DashboardPagesEditPageIdImport } from './routes/dashboard/pages/edit.$pageId'
import { Route as DashboardBlogEditBlogSlugImport } from './routes/dashboard/blog/edit.$blogSlug'

// Create/Update Routes

const NotFoundRoute = NotFoundImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const PublicLayoutRoute = PublicLayoutImport.update({
  id: '/_publicLayout',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)

const PublicLayoutIndexRoute = PublicLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any)

const DashboardUploadsRoute = DashboardUploadsImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardSettingsRoute = DashboardSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardSecurityRoute = DashboardSecurityImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardRoute,
} as any)

const PublicLayoutSignupRoute = PublicLayoutSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicLayoutRoute,
} as any)

const PublicLayoutLoginRoute = PublicLayoutLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicLayoutRoute,
} as any)

const PublicLayoutAboutRoute = PublicLayoutAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicLayoutRoute,
} as any)

const DashboardProjectsIndexRoute = DashboardProjectsIndexImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardPagesIndexRoute = DashboardPagesIndexImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardBlogIndexRoute = DashboardBlogIndexImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => DashboardRoute,
} as any)

const PublicLayoutProjectsIndexRoute = PublicLayoutProjectsIndexImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => PublicLayoutRoute,
} as any)

const PublicLayoutBlogIndexRoute = PublicLayoutBlogIndexImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PublicLayoutRoute,
} as any)

const DashboardProjectsNewRoute = DashboardProjectsNewImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardPagesNewRoute = DashboardPagesNewImport.update({
  id: '/pages/new',
  path: '/pages/new',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardBlogNewRoute = DashboardBlogNewImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => DashboardRoute,
} as any)

const PublicLayoutProjectsProjectIdRoute =
  PublicLayoutProjectsProjectIdImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => PublicLayoutRoute,
  } as any)

const PublicLayoutBlogBlogSlugRoute = PublicLayoutBlogBlogSlugImport.update({
  id: '/blog/$blogSlug',
  path: '/blog/$blogSlug',
  getParentRoute: () => PublicLayoutRoute,
} as any)

const DashboardProjectsEditProjectIdRoute =
  DashboardProjectsEditProjectIdImport.update({
    id: '/projects/edit/$projectId',
    path: '/projects/edit/$projectId',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardPagesEditPageIdRoute = DashboardPagesEditPageIdImport.update({
  id: '/pages/edit/$pageId',
  path: '/pages/edit/$pageId',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardBlogEditBlogSlugRoute = DashboardBlogEditBlogSlugImport.update({
  id: '/blog/edit/$blogSlug',
  path: '/blog/edit/$blogSlug',
  getParentRoute: () => DashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_publicLayout': {
      id: '/_publicLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicLayoutImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundImport
      parentRoute: typeof rootRoute
    }
    '/_publicLayout/about': {
      id: '/_publicLayout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicLayoutAboutImport
      parentRoute: typeof PublicLayoutImport
    }
    '/_publicLayout/login': {
      id: '/_publicLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLayoutLoginImport
      parentRoute: typeof PublicLayoutImport
    }
    '/_publicLayout/signup': {
      id: '/_publicLayout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicLayoutSignupImport
      parentRoute: typeof PublicLayoutImport
    }
    '/dashboard/security': {
      id: '/dashboard/security'
      path: '/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof DashboardSecurityImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/uploads': {
      id: '/dashboard/uploads'
      path: '/uploads'
      fullPath: '/dashboard/uploads'
      preLoaderRoute: typeof DashboardUploadsImport
      parentRoute: typeof DashboardImport
    }
    '/_publicLayout/': {
      id: '/_publicLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutIndexImport
      parentRoute: typeof PublicLayoutImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
    '/_publicLayout/blog/$blogSlug': {
      id: '/_publicLayout/blog/$blogSlug'
      path: '/blog/$blogSlug'
      fullPath: '/blog/$blogSlug'
      preLoaderRoute: typeof PublicLayoutBlogBlogSlugImport
      parentRoute: typeof PublicLayoutImport
    }
    '/_publicLayout/projects/$projectId': {
      id: '/_publicLayout/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof PublicLayoutProjectsProjectIdImport
      parentRoute: typeof PublicLayoutImport
    }
    '/dashboard/blog/new': {
      id: '/dashboard/blog/new'
      path: '/blog/new'
      fullPath: '/dashboard/blog/new'
      preLoaderRoute: typeof DashboardBlogNewImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/pages/new': {
      id: '/dashboard/pages/new'
      path: '/pages/new'
      fullPath: '/dashboard/pages/new'
      preLoaderRoute: typeof DashboardPagesNewImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/projects/new': {
      id: '/dashboard/projects/new'
      path: '/projects/new'
      fullPath: '/dashboard/projects/new'
      preLoaderRoute: typeof DashboardProjectsNewImport
      parentRoute: typeof DashboardImport
    }
    '/_publicLayout/blog/': {
      id: '/_publicLayout/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof PublicLayoutBlogIndexImport
      parentRoute: typeof PublicLayoutImport
    }
    '/_publicLayout/projects/': {
      id: '/_publicLayout/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof PublicLayoutProjectsIndexImport
      parentRoute: typeof PublicLayoutImport
    }
    '/dashboard/blog/': {
      id: '/dashboard/blog/'
      path: '/blog'
      fullPath: '/dashboard/blog'
      preLoaderRoute: typeof DashboardBlogIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/pages/': {
      id: '/dashboard/pages/'
      path: '/pages'
      fullPath: '/dashboard/pages'
      preLoaderRoute: typeof DashboardPagesIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/blog/edit/$blogSlug': {
      id: '/dashboard/blog/edit/$blogSlug'
      path: '/blog/edit/$blogSlug'
      fullPath: '/dashboard/blog/edit/$blogSlug'
      preLoaderRoute: typeof DashboardBlogEditBlogSlugImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/pages/edit/$pageId': {
      id: '/dashboard/pages/edit/$pageId'
      path: '/pages/edit/$pageId'
      fullPath: '/dashboard/pages/edit/$pageId'
      preLoaderRoute: typeof DashboardPagesEditPageIdImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/projects/edit/$projectId': {
      id: '/dashboard/projects/edit/$projectId'
      path: '/projects/edit/$projectId'
      fullPath: '/dashboard/projects/edit/$projectId'
      preLoaderRoute: typeof DashboardProjectsEditProjectIdImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

interface PublicLayoutRouteChildren {
  PublicLayoutAboutRoute: typeof PublicLayoutAboutRoute
  PublicLayoutLoginRoute: typeof PublicLayoutLoginRoute
  PublicLayoutSignupRoute: typeof PublicLayoutSignupRoute
  PublicLayoutIndexRoute: typeof PublicLayoutIndexRoute
  PublicLayoutBlogBlogSlugRoute: typeof PublicLayoutBlogBlogSlugRoute
  PublicLayoutProjectsProjectIdRoute: typeof PublicLayoutProjectsProjectIdRoute
  PublicLayoutBlogIndexRoute: typeof PublicLayoutBlogIndexRoute
  PublicLayoutProjectsIndexRoute: typeof PublicLayoutProjectsIndexRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicLayoutAboutRoute: PublicLayoutAboutRoute,
  PublicLayoutLoginRoute: PublicLayoutLoginRoute,
  PublicLayoutSignupRoute: PublicLayoutSignupRoute,
  PublicLayoutIndexRoute: PublicLayoutIndexRoute,
  PublicLayoutBlogBlogSlugRoute: PublicLayoutBlogBlogSlugRoute,
  PublicLayoutProjectsProjectIdRoute: PublicLayoutProjectsProjectIdRoute,
  PublicLayoutBlogIndexRoute: PublicLayoutBlogIndexRoute,
  PublicLayoutProjectsIndexRoute: PublicLayoutProjectsIndexRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

interface DashboardRouteChildren {
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUploadsRoute: typeof DashboardUploadsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBlogNewRoute: typeof DashboardBlogNewRoute
  DashboardPagesNewRoute: typeof DashboardPagesNewRoute
  DashboardProjectsNewRoute: typeof DashboardProjectsNewRoute
  DashboardBlogIndexRoute: typeof DashboardBlogIndexRoute
  DashboardPagesIndexRoute: typeof DashboardPagesIndexRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  DashboardBlogEditBlogSlugRoute: typeof DashboardBlogEditBlogSlugRoute
  DashboardPagesEditPageIdRoute: typeof DashboardPagesEditPageIdRoute
  DashboardProjectsEditProjectIdRoute: typeof DashboardProjectsEditProjectIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUploadsRoute: DashboardUploadsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBlogNewRoute: DashboardBlogNewRoute,
  DashboardPagesNewRoute: DashboardPagesNewRoute,
  DashboardProjectsNewRoute: DashboardProjectsNewRoute,
  DashboardBlogIndexRoute: DashboardBlogIndexRoute,
  DashboardPagesIndexRoute: DashboardPagesIndexRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  DashboardBlogEditBlogSlugRoute: DashboardBlogEditBlogSlugRoute,
  DashboardPagesEditPageIdRoute: DashboardPagesEditPageIdRoute,
  DashboardProjectsEditProjectIdRoute: DashboardProjectsEditProjectIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof PublicLayoutRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/not-found': typeof NotFoundRoute
  '/about': typeof PublicLayoutAboutRoute
  '/login': typeof PublicLayoutLoginRoute
  '/signup': typeof PublicLayoutSignupRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/uploads': typeof DashboardUploadsRoute
  '/': typeof PublicLayoutIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/blog/$blogSlug': typeof PublicLayoutBlogBlogSlugRoute
  '/projects/$projectId': typeof PublicLayoutProjectsProjectIdRoute
  '/dashboard/blog/new': typeof DashboardBlogNewRoute
  '/dashboard/pages/new': typeof DashboardPagesNewRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/blog': typeof PublicLayoutBlogIndexRoute
  '/projects': typeof PublicLayoutProjectsIndexRoute
  '/dashboard/blog': typeof DashboardBlogIndexRoute
  '/dashboard/pages': typeof DashboardPagesIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/blog/edit/$blogSlug': typeof DashboardBlogEditBlogSlugRoute
  '/dashboard/pages/edit/$pageId': typeof DashboardPagesEditPageIdRoute
  '/dashboard/projects/edit/$projectId': typeof DashboardProjectsEditProjectIdRoute
}

export interface FileRoutesByTo {
  '/not-found': typeof NotFoundRoute
  '/about': typeof PublicLayoutAboutRoute
  '/login': typeof PublicLayoutLoginRoute
  '/signup': typeof PublicLayoutSignupRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/uploads': typeof DashboardUploadsRoute
  '/': typeof PublicLayoutIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/blog/$blogSlug': typeof PublicLayoutBlogBlogSlugRoute
  '/projects/$projectId': typeof PublicLayoutProjectsProjectIdRoute
  '/dashboard/blog/new': typeof DashboardBlogNewRoute
  '/dashboard/pages/new': typeof DashboardPagesNewRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/blog': typeof PublicLayoutBlogIndexRoute
  '/projects': typeof PublicLayoutProjectsIndexRoute
  '/dashboard/blog': typeof DashboardBlogIndexRoute
  '/dashboard/pages': typeof DashboardPagesIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/blog/edit/$blogSlug': typeof DashboardBlogEditBlogSlugRoute
  '/dashboard/pages/edit/$pageId': typeof DashboardPagesEditPageIdRoute
  '/dashboard/projects/edit/$projectId': typeof DashboardProjectsEditProjectIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_publicLayout': typeof PublicLayoutRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/not-found': typeof NotFoundRoute
  '/_publicLayout/about': typeof PublicLayoutAboutRoute
  '/_publicLayout/login': typeof PublicLayoutLoginRoute
  '/_publicLayout/signup': typeof PublicLayoutSignupRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/uploads': typeof DashboardUploadsRoute
  '/_publicLayout/': typeof PublicLayoutIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_publicLayout/blog/$blogSlug': typeof PublicLayoutBlogBlogSlugRoute
  '/_publicLayout/projects/$projectId': typeof PublicLayoutProjectsProjectIdRoute
  '/dashboard/blog/new': typeof DashboardBlogNewRoute
  '/dashboard/pages/new': typeof DashboardPagesNewRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/_publicLayout/blog/': typeof PublicLayoutBlogIndexRoute
  '/_publicLayout/projects/': typeof PublicLayoutProjectsIndexRoute
  '/dashboard/blog/': typeof DashboardBlogIndexRoute
  '/dashboard/pages/': typeof DashboardPagesIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/blog/edit/$blogSlug': typeof DashboardBlogEditBlogSlugRoute
  '/dashboard/pages/edit/$pageId': typeof DashboardPagesEditPageIdRoute
  '/dashboard/projects/edit/$projectId': typeof DashboardProjectsEditProjectIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/dashboard'
    | '/not-found'
    | '/about'
    | '/login'
    | '/signup'
    | '/dashboard/security'
    | '/dashboard/settings'
    | '/dashboard/uploads'
    | '/'
    | '/dashboard/'
    | '/blog/$blogSlug'
    | '/projects/$projectId'
    | '/dashboard/blog/new'
    | '/dashboard/pages/new'
    | '/dashboard/projects/new'
    | '/blog'
    | '/projects'
    | '/dashboard/blog'
    | '/dashboard/pages'
    | '/dashboard/projects'
    | '/dashboard/blog/edit/$blogSlug'
    | '/dashboard/pages/edit/$pageId'
    | '/dashboard/projects/edit/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/not-found'
    | '/about'
    | '/login'
    | '/signup'
    | '/dashboard/security'
    | '/dashboard/settings'
    | '/dashboard/uploads'
    | '/'
    | '/dashboard'
    | '/blog/$blogSlug'
    | '/projects/$projectId'
    | '/dashboard/blog/new'
    | '/dashboard/pages/new'
    | '/dashboard/projects/new'
    | '/blog'
    | '/projects'
    | '/dashboard/blog'
    | '/dashboard/pages'
    | '/dashboard/projects'
    | '/dashboard/blog/edit/$blogSlug'
    | '/dashboard/pages/edit/$pageId'
    | '/dashboard/projects/edit/$projectId'
  id:
    | '__root__'
    | '/_publicLayout'
    | '/dashboard'
    | '/not-found'
    | '/_publicLayout/about'
    | '/_publicLayout/login'
    | '/_publicLayout/signup'
    | '/dashboard/security'
    | '/dashboard/settings'
    | '/dashboard/uploads'
    | '/_publicLayout/'
    | '/dashboard/'
    | '/_publicLayout/blog/$blogSlug'
    | '/_publicLayout/projects/$projectId'
    | '/dashboard/blog/new'
    | '/dashboard/pages/new'
    | '/dashboard/projects/new'
    | '/_publicLayout/blog/'
    | '/_publicLayout/projects/'
    | '/dashboard/blog/'
    | '/dashboard/pages/'
    | '/dashboard/projects/'
    | '/dashboard/blog/edit/$blogSlug'
    | '/dashboard/pages/edit/$pageId'
    | '/dashboard/projects/edit/$projectId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  NotFoundRoute: typeof NotFoundRoute
}

const rootRouteChildren: RootRouteChildren = {
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  NotFoundRoute: NotFoundRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_publicLayout",
        "/dashboard",
        "/not-found"
      ]
    },
    "/_publicLayout": {
      "filePath": "_publicLayout.tsx",
      "children": [
        "/_publicLayout/about",
        "/_publicLayout/login",
        "/_publicLayout/signup",
        "/_publicLayout/",
        "/_publicLayout/blog/$blogSlug",
        "/_publicLayout/projects/$projectId",
        "/_publicLayout/blog/",
        "/_publicLayout/projects/"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard.tsx",
      "children": [
        "/dashboard/security",
        "/dashboard/settings",
        "/dashboard/uploads",
        "/dashboard/",
        "/dashboard/blog/new",
        "/dashboard/pages/new",
        "/dashboard/projects/new",
        "/dashboard/blog/",
        "/dashboard/pages/",
        "/dashboard/projects/",
        "/dashboard/blog/edit/$blogSlug",
        "/dashboard/pages/edit/$pageId",
        "/dashboard/projects/edit/$projectId"
      ]
    },
    "/not-found": {
      "filePath": "not-found.tsx"
    },
    "/_publicLayout/about": {
      "filePath": "_publicLayout/about.tsx",
      "parent": "/_publicLayout"
    },
    "/_publicLayout/login": {
      "filePath": "_publicLayout/login.tsx",
      "parent": "/_publicLayout"
    },
    "/_publicLayout/signup": {
      "filePath": "_publicLayout/signup.tsx",
      "parent": "/_publicLayout"
    },
    "/dashboard/security": {
      "filePath": "dashboard/security.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/settings": {
      "filePath": "dashboard/settings.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/uploads": {
      "filePath": "dashboard/uploads.tsx",
      "parent": "/dashboard"
    },
    "/_publicLayout/": {
      "filePath": "_publicLayout/index.tsx",
      "parent": "/_publicLayout"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/_publicLayout/blog/$blogSlug": {
      "filePath": "_publicLayout/blog/$blogSlug.tsx",
      "parent": "/_publicLayout"
    },
    "/_publicLayout/projects/$projectId": {
      "filePath": "_publicLayout/projects/$projectId.tsx",
      "parent": "/_publicLayout"
    },
    "/dashboard/blog/new": {
      "filePath": "dashboard/blog/new.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/pages/new": {
      "filePath": "dashboard/pages/new.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/projects/new": {
      "filePath": "dashboard/projects/new.tsx",
      "parent": "/dashboard"
    },
    "/_publicLayout/blog/": {
      "filePath": "_publicLayout/blog/index.tsx",
      "parent": "/_publicLayout"
    },
    "/_publicLayout/projects/": {
      "filePath": "_publicLayout/projects/index.tsx",
      "parent": "/_publicLayout"
    },
    "/dashboard/blog/": {
      "filePath": "dashboard/blog/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/pages/": {
      "filePath": "dashboard/pages/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/projects/": {
      "filePath": "dashboard/projects/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/blog/edit/$blogSlug": {
      "filePath": "dashboard/blog/edit.$blogSlug.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/pages/edit/$pageId": {
      "filePath": "dashboard/pages/edit.$pageId.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/projects/edit/$projectId": {
      "filePath": "dashboard/projects/edit.$projectId.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
