package dto

import (
	"time"

	"github.com/google/uuid"
)

// InsightTopicCreateRequest represents a request to create a topic
type InsightTopicCreateRequest struct {
	Name        string   `json:"name" validate:"required,min=1,max=255"`
	Description *string  `json:"description"`
	Keywords    []string `json:"keywords"`
	Color       *string  `json:"color" validate:"omitempty,max=20"`
	Icon        *string  `json:"icon" validate:"omitempty,max=50"`
}

// InsightTopicUpdateRequest represents a request to update a topic
type InsightTopicUpdateRequest struct {
	Name        *string  `json:"name" validate:"omitempty,min=1,max=255"`
	Description *string  `json:"description"`
	Keywords    []string `json:"keywords"`
	Color       *string  `json:"color" validate:"omitempty,max=20"`
	Icon        *string  `json:"icon" validate:"omitempty,max=50"`
}

// InsightTopicResponse is the response for an insight topic
type InsightTopicResponse struct {
	ID              uuid.UUID  `json:"id"`
	OrganizationID  *uuid.UUID `json:"organization_id,omitempty"`
	Name            string     `json:"name"`
	Description     *string    `json:"description,omitempty"`
	Keywords        []string   `json:"keywords"`
	IsAutoGenerated bool       `json:"is_auto_generated"`
	ContentCount    int        `json:"content_count"`
	LastInsightAt   *time.Time `json:"last_insight_at,omitempty"`
	Color           *string    `json:"color,omitempty"`
	Icon            *string    `json:"icon,omitempty"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

// InsightResponse is the response for an insight
type InsightResponse struct {
	ID               uuid.UUID              `json:"id"`
	OrganizationID   *uuid.UUID             `json:"organization_id,omitempty"`
	TopicID          *uuid.UUID             `json:"topic_id,omitempty"`
	Title            string                 `json:"title"`
	Summary          string                 `json:"summary"`
	Content          *string                `json:"content,omitempty"`
	KeyPoints        []string               `json:"key_points"`
	SourceContentIDs []uuid.UUID            `json:"source_content_ids"`
	GeneratedAt      time.Time              `json:"generated_at"`
	PeriodStart      *time.Time             `json:"period_start,omitempty"`
	PeriodEnd        *time.Time             `json:"period_end,omitempty"`
	IsRead           bool                   `json:"is_read"`
	IsPinned         bool                   `json:"is_pinned"`
	IsUsedInArticle  bool                   `json:"is_used_in_article"`
	MetaData         map[string]interface{} `json:"meta_data,omitempty"`
	// Joined fields
	TopicName  *string `json:"topic_name,omitempty"`
	TopicColor *string `json:"topic_color,omitempty"`
	TopicIcon  *string `json:"topic_icon,omitempty"`
}

// InsightSearchRequest represents a request to search insights
type InsightSearchRequest struct {
	Query    string     `json:"query" validate:"required,min=1"`
	TopicID  *uuid.UUID `json:"topic_id"`
	Limit    int        `json:"limit" validate:"omitempty,min=1,max=50"`
	IsUnread *bool      `json:"is_unread"`
}

// UserInsightStatusResponse is the response for user insight status
type UserInsightStatusResponse struct {
	InsightID       uuid.UUID  `json:"insight_id"`
	IsRead          bool       `json:"is_read"`
	IsPinned        bool       `json:"is_pinned"`
	IsUsedInArticle bool       `json:"is_used_in_article"`
	ReadAt          *time.Time `json:"read_at,omitempty"`
}

// InsightWithUserStatus combines an insight with user-specific status
type InsightWithUserStatus struct {
	InsightResponse
	UserStatus *UserInsightStatusResponse `json:"user_status,omitempty"`
}

// InsightWithSources includes the insight with its source content
type InsightWithSources struct {
	ID               uuid.UUID              `json:"id"`
	OrganizationID   *uuid.UUID             `json:"organization_id,omitempty"`
	TopicID          *uuid.UUID             `json:"topic_id,omitempty"`
	Title            string                 `json:"title"`
	Summary          string                 `json:"summary"`
	Content          *string                `json:"content,omitempty"`
	KeyPoints        []string               `json:"key_points"`
	SourceContentIDs []uuid.UUID            `json:"source_content_ids"`
	GeneratedAt      time.Time              `json:"generated_at"`
	PeriodStart      *time.Time             `json:"period_start,omitempty"`
	PeriodEnd        *time.Time             `json:"period_end,omitempty"`
	IsRead           bool                   `json:"is_read"`
	IsPinned         bool                   `json:"is_pinned"`
	IsUsedInArticle  bool                   `json:"is_used_in_article"`
	MetaData         map[string]interface{} `json:"meta_data,omitempty"`
	SourceContents   []CrawledContentResponse `json:"source_contents"`
	Topic            *InsightTopicResponse    `json:"topic,omitempty"`
}
